<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Admin\**" />
    <EmbeddedResource Remove="Admin\**" />
    <None Remove="Admin\**" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Mvc\SEO\JSON\IAttributeWebApiClient.GetAttributeVocabularyValues.tenant~brand.json" />
    <None Remove="Mvc\SEO\JSON\IAttributeWebApiClient.GetAttributeVocabularyValues.tenant~colorgroup.json" />
    <None Remove="Mvc\SEO\JSON\IGeneralSettingsWebApiClient.GetGeneralSettings.json" />
    <None Remove="Mvc\SEO\JSON\IProductCategoryRuntimeWebApiClient.GetCategoryTree.json" />
    <None Remove="Mvc\SEO\JSON\IProductSearchWebApiClient.Search.tenant~brand.json" />
    <None Remove="Mvc\SEO\JSON\IProductSearchWebApiClient.Search.tenant~colorgroup.json" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Mvc\SEO\JSON\IAttributeWebApiClient.GetAttributeVocabularyValues.tenant~brand.json" />
    <EmbeddedResource Include="Mvc\SEO\JSON\IAttributeWebApiClient.GetAttributeVocabularyValues.tenant~colorgroup.json" />
    <EmbeddedResource Include="Mvc\SEO\JSON\IGeneralSettingsWebApiClient.GetGeneralSettings.json" />
    <EmbeddedResource Include="Mvc\SEO\JSON\IProductCategoryRuntimeWebApiClient.GetCategoryTree.json" />
    <EmbeddedResource Include="Mvc\SEO\JSON\IProductSearchWebApiClient.Search.tenant~brand.json" />
    <EmbeddedResource Include="Mvc\SEO\JSON\IProductSearchWebApiClient.Search.tenant~colorgroup.json" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="JUnitTestLogger" Version="1.1.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.6.1" />
    <PackageReference Include="Mozu.Core.Api.Test" Version="1.2021.18" />
    <PackageReference Include="Mozu.Core.JunitTestLogger" Version="1.2021.18" />
    <PackageReference Include="Mozu.Core.Prime" Version="1.2021.18" />
    <PackageReference Include="Mozu.Core.Test" Version="1.2021.18" />
    <PackageReference Include="NUnit" Version="3.12.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.16.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Mozu.SiteBuilder.Mvc\Mozu.SiteBuilder.Mvc.csproj" />
    <ProjectReference Include="..\Mozu.SiteBuilder.UX.Models\Mozu.SiteBuilder.UX.Models.csproj" />
    <ProjectReference Include="..\Mozu.SiteBuilder.UX\Mozu.SiteBuilder.UX.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>
</Project>