var util = require('util'),
    fs = require('fs'),
    path = require('path'),
    Q = require('q'),
    FSUtils = require('../fsutils'),
    color = require('cli-color'),
    _ = require('underscore'),
    xmlbuilder = require('xmlbuilder'),
    Lyrically = require('../lyrically');

function createXmlFromVars(context, deferred) {
    var styleSheetsDir = context.inheritedTheme.getPath('stylesheets'),
        detectedSettings = [];
    try {
        var walker = FSUtils.walkDir(styleSheetsDir);

        walker.on('file,', function (root, stylesheet, next) {
            var ext = path.extname(stylesheet);
            if (ext === ".less" || ext === ".css") {
                _.each(_.uniq(fs.readFileSync(path.resolve(root, stylesheet), 'utf8').match(/\{\{.+\}\}/gm)),
                    function(tag) {
                        var settingName = tag.match(/\.(\w+)/)[1],
                            setting = _.find(detectedSettings, function(s){
                                return s.name === settingName;
                            }),
                            piped = tag.replace(/\}\}$/,'').split('|');
                        if (!setting) {
                            setting = {};
                            detectedSettings.push(setting);
                        }
                        setting.name = settingName;
                        if (piped.length > 0) {
                            piped.shift(); // discard first bit
                            _.each(piped,function(fil){
                                var m = fil.match(/^(\w+)(?:\:(.*))?$/);
                                if (!m || m.length < 2 || m.length > 3) {
                                    Lyrically.lament("Problem parsing tag \n" + tag + "\n in file \n" + stylesheet);
                                    return;
                                }
                                var k = m[1],
                                    v = m.length === 3 ? m[2] : true; // filters with no arguments simply add the filter name as a boolean true.
                                if (k in setting) {
                                    Lyrically.whine("Theme setting " + settingName + " declared with " + k + " more than once. Saving as " + v);
                                }
                                try {
                                    v = (new Function('return ' + v))();
                                } catch(e) {}
                                setting[k] = v;
                            });
                        }
                        setting.group = setting.group || setting.settingtype || 'General';
                        setting.settingtype = setting.settingtype || 'textbox';
                });
            }
            next();
        });

        walker.on('end', function () {
            detectedSettings = _.groupBy(detectedSettings, 'group');
            //util.puts(util.inspect(detectedSettings,true,5,true));

            var xmlDoc = xmlbuilder.create('settings', { 'version': '1.0' })
                .att('xmlns:xsd', 'http://www.w3.org/2001/XMLSchema')
                .att('xmlns:xsi', 'http://www.w3.org/2001/XMLSchema-instance')
                .att('xsi:noNamespaceSchemaLocation', '..\\..\\..\\Tools\\ThemeSettings.xsd'),

                items = xmlDoc.ele('items');

            _.each(detectedSettings, function (group, groupName) {
                var section = items.ele('section', {
                    'id': groupName,
                    'label': groupName.charAt(0).toUpperCase() + groupName.slice(1),
                    'visible': true
                }).ele('items');
                _.each(group, function (setting) {
                    var settingNode = section.ele('setting', {
                        'id': setting.name,
                        'type': setting.settingtype,
                        'label': setting.description,
                        'defaultValue': setting['default']
                    });
                    if (setting.values) {
                        var valuesNode = settingNode.ele('values');
                        for (var i = setting.values.length - 1; i >= 0; i--) {
                            valuesNode.ele('option', setting.values[i], { 'value': setting.values[i] });
                        }
                    }
                });
            });
            fs.writeFile(context.theme.getPath('settings'), xmlDoc.end({ 'pretty': true }), function (err) {
                if (err) {
                    Lyrically.lament("Error while writing ThemeSettings.xml file.")
                    deferred.reject(err);
                } else {
                    Lyrically.admit('Theme settings autogenerated as ThemeSettings.xml');
                    deferred.resolve();
                }
            });
        });

    } catch (e) {
        Lyrically.lament("Error during stylesheet assembly!");
        deferred.reject(e);
    }
}



module.exports = function () {

    Lyrically.whine("Theme settings autogen sorta implemented");

    var self = this,
        deferred = Q.defer();

    function promptForOverwrite() {
        Lyrically.whine("There is already a ThemeSettings.xml file. Autogenerating one will overwrite it.");
        self.program.confirm(color.yellowBright(" Type 'yes' to overwrite " + self.theme.getPath('settings') + ".\n Press ENTER ") + color.yellowBright.bold("twice") + color.yellowBright(" when done."), function (yes) {
            if (yes) {
                createXmlFromVars(self,deferred);
            } else {
                Lyrically.note("Skipping autogeneration of theme settings XML.");
                deferred.resolve();
            }
        });
    }

    if (self.theme.has('settings')) {
        if (self.program.buildJs && self.program.verbose) {
            // wait until jsbuild is over, so the logging doesn't scroll the prompt out of view
            self.taskDict.buildJs.then(promptForOverwrite);
        } else {
            promptForOverwrite();
        }
    } else {
        createXmlFromVars(self,deferred);
    }
    return deferred.promise;
};