<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="DeviceDetector.NET" Version="4.2.0" />
    <PackageReference Include="Mozu.AdminUser.Contracts" Version="1.2013.2" />
    <PackageReference Include="Mozu.CommerceRuntime.Contracts" Version="1.2113.2" />
    <PackageReference Include="Mozu.Content.Contracts" Version="1.1917.0-dotnetcore.28" />
    <PackageReference Include="Mozu.Core.Extensible.Contracts" Version="1.2005.1" />
    <PackageReference Include="Mozu.Core.Messaging" Version="1.2031.2" />
    <PackageReference Include="Mozu.Core.Messaging.Contracts" Version="1.2031.2" />
    <PackageReference Include="Mozu.Core.Prime" Version="1.2113.2" />

    <PackageReference Include="Mozu.Customer.Contracts" Version="1.2113.2" />
    <PackageReference Include="Mozu.DNS.Contracts" Version="1.1915.0-dotnetcore.2" />
    <PackageReference Include="Mozu.InstalledApplications.Contracts" Version="1.1915.0-dotnetcore.4" />
    <PackageReference Include="Mozu.Location.Contracts" Version="1.2031.2" />
    <PackageReference Include="Mozu.MZDB.Contracts" Version="1.1928.0-dotnetcore.48" />
    <PackageReference Include="Mozu.PaymentService.Contracts" Version="1.2010.0-dotnetcorecontracts.11" />
    <PackageReference Include="Mozu.PricingRuntime.Contracts" Version="1.2108.2" />
    <PackageReference Include="Mozu.ProductAdmin.Contracts" Version="1.2108.2" />
    <PackageReference Include="Mozu.ProductRuntime.Contracts" Version="1.2108.2" />
    <PackageReference Include="Mozu.Provisioning.Contracts" Version="1.1943.0-dotnetcore.78" />
    <PackageReference Include="Mozu.Reference.Contracts" Version="1.2013.2" />
    <PackageReference Include="Mozu.ShippingAdmin.Contracts" Version="1.2005.0-plat-153.2" />
    <PackageReference Include="Mozu.SiteSettings.Contracts" Version="1.2037.2" />
    <PackageReference Include="Mozu.SiteSettings.General.Contracts" Version="1.2037.2" />
    <PackageReference Include="Mozu.Tenant.Contracts" Version="1.1942.0-dotnetcore.42" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>
</Project>
