# =============================================================================
# This file defines properties used by build-impl.xml, which is the core of
# the applications build process. You can customize this file to control the
# various options used in the build.
#
# IMPORTANT - Sencha Cmd will merge your changes with its own during upgrades.
# To avoid potential merge conflicts avoid making large, sweeping changes to
# this file.
# =============================================================================



# ===========================================
# various sass / css properties
# ===========================================

app.out.css=${build.dir}/resources/css/${app.out.css.rel}
app.out.css.compressed=${build.dir}/resources/css/${app.out.base}.css

