<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="MessageHandler\FourHundredMessageHandler.cs" />
    <Compile Remove="MessageHandler\HttpContextInjectingMessageHandler.cs" />
    <Compile Remove="MessageHandler\ResponseHeaderAppenderMessagHandler.cs" />
    <Compile Remove="MessageHandler\SbSessionHandler.cs" />
    <Compile Remove="MessageHandler\SeoDelegatingHandler.cs" />
    <Compile Remove="MessageHandler\SessionHandler.cs" />
    <Compile Remove="MessageHandler\SiteBuilderRouteDataInitilizer.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FSPowerPack.Core.Community" Version="3.0.0" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Core" Version="5.2.7" />
    <PackageReference Include="Mozu.AdminUser.Contracts" Version="1.1952.0-dotnetcore.136" />
    <PackageReference Include="Mozu.AppDev.Contracts" Version="1.1944.0-ddlogs2.9" />
    <PackageReference Include="Mozu.Content.Contracts" Version="1.1917.0-dotnetcore.28" />
    <PackageReference Include="Mozu.Core.Actions" Version="1.2005.8" />
    <PackageReference Include="Mozu.Core.Expressions" Version="1.2005.1" />
    <PackageReference Include="Mozu.Core.Extensible.Contracts" Version="1.2005.1" />
    <PackageReference Include="Mozu.Core.Messaging" Version="1.2005.1" />
    <PackageReference Include="Mozu.Core.Messaging.Contracts" Version="1.2005.1" />
    <PackageReference Include="Mozu.Core.Prime" Version="1.2005.6" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="5.5.6" />
    <PackageReference Include="Mozu.Customer.Contracts" Version="1.1929.0-dotnetcore.26" />
    <PackageReference Include="Mozu.DNS.Contracts" Version="1.1915.0-dotnetcore.2" />
    <PackageReference Include="Mozu.InstalledApplications.Contracts" Version="1.1915.0-dotnetcore.4" />
    <PackageReference Include="Mozu.Location.Contracts" Version="1.2005.0-pr-7.3" />
    <PackageReference Include="Mozu.MZDB.Contracts" Version="1.1928.0-dotnetcore.48" />
    <PackageReference Include="Mozu.PaymentService.Contracts" Version="1.1930.0-dotnetcorecontracts.10" />
    <PackageReference Include="Mozu.PricingRuntime.Contracts" Version="1.2006.0-pr-15.7" />
    <PackageReference Include="Mozu.ProductAdmin.Contracts" Version="1.2006.0-pr-15.7" />
    <PackageReference Include="Mozu.ProductRuntime.Contracts" Version="1.2006.0-pr-15.7" />
    <PackageReference Include="Mozu.Provisioning.Contracts" Version="1.1943.0-dotnetcore.78" />
    <PackageReference Include="Mozu.Reference.Contracts" Version="1.1941.0-dotnetcore.21" />
    <PackageReference Include="Mozu.ShippingAdmin.Contracts" Version="1.2005.0-plat-153.2" />
    <PackageReference Include="Mozu.ShippingRuntime.Contracts" Version="1.1939.0-dotnetcore.46" />
    <PackageReference Include="Mozu.SiteSettings.Contracts" Version="1.2004.0-dotnetcore.74" />
    <PackageReference Include="Mozu.Tenant.Contracts" Version="1.1942.0-dotnetcore.42" />
    <PackageReference Include="NDjangoParser40" Version="1.2008.0-dotnetcore.2" />
    <PackageReference Include="NDjangoParserFilters40" Version="1.2008.0-dotnetcore.2" />
    <PackageReference Include="System.ServiceModel.Syndication" Version="4.7.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mozu.SiteBuilder.UX.Models\Mozu.SiteBuilder.UX.Models.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="MessageHandler\" />
    <Folder Include="Properties\" />
  </ItemGroup>

</Project>