<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
     <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>


  <ItemGroup>
    <Compile Remove="MessageHandler\FourHundredMessageHandler.cs" />
    <Compile Remove="MessageHandler\HttpContextInjectingMessageHandler.cs" />
    <Compile Remove="MessageHandler\ResponseHeaderAppenderMessagHandler.cs" />
    <Compile Remove="MessageHandler\SbSessionHandler.cs" />
    <Compile Remove="MessageHandler\SeoDelegatingHandler.cs" />
    <Compile Remove="MessageHandler\SessionHandler.cs" />
    <Compile Remove="MessageHandler\SiteBuilderRouteDataInitilizer.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DeviceDetector.NET" Version="6.3.3" />
    <PackageReference Include="FSPowerPack.Core.Community" Version="3.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="6.0.32" />
    <PackageReference Include="Mozu.Core.Expressions" Version="1.2005.1" />
    <PackageReference Include="Mozu.Core.Prime" Version="2.2540.1" />
    <PackageReference Include="Mozu.Reference.Contracts" Version="1.2113.2" />
    <PackageReference Include="Mozu.Tenant.Contracts" Version="1.2410.2" />
    <PackageReference Include="NDjangoParser40" Version="1.2019.0-pr-1.1" />
    <PackageReference Include="NDjangoParserFilters40" Version="1.2019.0-pr-1.1" />
    <PackageReference Include="System.ServiceModel.Syndication" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mozu.SiteBuilder.UX.Models\Mozu.SiteBuilder.UX.Models.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="MessageHandler\" />
    <Folder Include="Properties\" />
  </ItemGroup>

  <ItemGroup>
    <Folder Remove="TestData" />

    <EmbeddedResource Include="TestData\**\*.json" />

    <None Remove="ArcJsExtensions\Content\dist\webpack.bundle.js" />

    <None Remove="TestData\backoffice\Account.json" />

    <None Remove="TestData\backoffice\b2bUsers.json" />

    <None Remove="TestData\backoffice\PickwaveDetails.json" />

    <None Remove="TestData\backoffice\shipment-for-gift-receipt.json" />

    <None Remove="TestData\order.changed\Order1.json" />

    <None Remove="TestData\order.itemscanceled\Order1.json" />

    <None Remove="TestData\order.itemssubstituted\Order1.json" />
    <None Remove="TestData\shipment.transfercreatedbyfulfiller\Location1.json" />

    <None Remove="TestData\shipment.transfercreatedbyfulfiller\Shipment1.json" />

    <None Remove="TestData\subscription.reactivationreminder\subscription1.json" />
    <None Remove="TestData\subscription.pausereminder\subscription1.json" />

    <EmbeddedResource Include="ArcJsExtensions\Content\dist\webpack.bundle.js" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="TestData\backoffice\Shipment3.json" />
  </ItemGroup>
</Project>