
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  "Taco.view.productOption.Edit": "app/view/productOption/edit.js",
  "Ext.ux.IFrame": "ux/IFrame.js",
  "Taco.view.website.settings.facets.FacetRangeQueryForm": "app/view/website/settings/Facets/FacetRangeQueryForm.js",
  "Taco.store.OrderItems": "app/store/CartItems.js",
  "Taco.core.CTemplate": "app/core/util/CTemplate.js",
  "Ext.rtl.EventObjectImpl": "ext/src/rtl/EventObject.js",
  "Ext.ux.form.SearchField": "ext/src/ux/form/SearchField.js",
  "Taco.view.website.settings.facets.Facets": "app/view/website/settings/Facets/Facets.js",
  "Taco.view.website.settings.facets.FacetRangeQuery": "app/view/website/settings/Facets/FacetRangeQuery.js",
  "Ext.ux.RowExpander": "ux/RowExpander.js",
  "Taco.Application": "app/application.js",
  "Taco.view.themesettings.Section": "app/view/themeSettings/Section.js",
  "Taco.view.website.settings.facets.FacetRangeQueryGroup": "app/view/website/settings/Facets/FacetRangeQueryGroup.js",
  " Ext.Msg": "ext/src/window/MessageBox.js",
  "Ext.ux.form": "ux/form",
  "Ext": "ext/src",
  "Taco": "app",
  "Ext.ux.layout.component.field.BoxSelectField": "ux/form/field/BoxSelect.js",
  "Taco.view.themesettings.Index": "app/view/themeSettings/Index.js",
  "Taco.view.generalsettings.Form": "app/view/generalSettings/Form.js",
  "MyReader": "app/view/report/Index.js",
  "Taco.view.themesettings.Group": "app/view/themeSettings/Group.js",
  "Taco.view.themesettings.Addons": "app/view/themeSettings/Addons.js",
  "Taco.core.data.AjaxProxy": "app/core/AjaxProxy.js"
});
Ext.ClassManager.addNameAlternateMappings({
  "Taco.view.redirects.Index": [],
  "Taco.view.settings.paymentAndCheckout.Gateway": [],
  "Taco.model.CustomerGroupComboBox": [],
  "Taco.core.ux.browser.BrowserPage": [],
  "Taco.view.testing.StandaloneOption": [],
  "Taco.view.attribute.Edit": [],
  "Taco.core.ux.action.SplitButton": [],
  "Taco.core.ux.CardPanel": [],
  "Taco.view.website.entityAdapters.SiteTemplateEntityAdapter": [],
  "Taco.store.ProductTypes": [],
  "Taco.controller.Capability": [],
  "Taco.store.Options": [],
  "Taco.core.ux.form.field.InlinePicker": [],
  "Taco.view.fileManager.Index": [],
  "Taco.view.order.Form": [],
  "Ext.ux.layout.component.field.BoxSelectField": [],
  "Taco.view.website.entityAdapters.EmailTemplateEntityAdapter": [],
  "Taco.view.order.widget.PaymentPanel": [],
  "Taco.core.context.MasterCatalog": [],
  "Taco.view.pendingChange.Cms": [],
  "Taco.core.ux.BaseGrid": [],
  "Taco.view.order.subform.Detail": [],
  "Taco.model.OrderItem": [],
  "Taco.view.website.settings.facets.FacetRangeQuery": [],
  "Taco.shared.view.field.ProductPickerField": [],
  "Taco.core.ux.window.Window": [],
  "Taco.view.customerAttribute.Form": [],
  "Taco.model.FacetSet": [],
  "Taco.view.website.settings.facets.FacetRangeQueryGroup": [],
  "Taco.core.ux.window.MessageBox": [],
  "Taco.view.productType.AttributeForm": [],
  "Taco.view.website.settings.General": [],
  "Taco.view.website.Tree": [],
  "Taco.view.error.Index": [],
  "Taco.core.util.FileUploadEvent": [],
  "Taco.shared.view.field.CountryField": [],
  "Taco.model.OptionValue": [],
  "Ext.ux.ajax.Simlet": [],
  "Taco.view.customers.Edit": [],
  "Taco.core.ux.mixins.Pageable": [],
  "Taco.core.ux.BaseCardPanel": [],
  "Taco.model.GeneralSettings": [],
  "Taco.core.ux.grid.MenuColumn": [],
  "Taco.model.ProductTypeAttribute": [],
  "Taco.core.ux.content.Container": [],
  "Taco.view.customers.AdvancedSearchForm": [],
  "Taco.controller.Categories": [],
  "Taco.view.order.widget.ShippingItemGrid": [],
  "Taco.model.ProductOptionValue": [],
  "Taco.view.product.subform.Shipping": [],
  "Taco.core.ux.EditPanel": [],
  "Taco.view.generalSettings.subform.Maintenance": [],
  "Taco.view.navigation.ContextSwitcher": [],
  "Taco.view.error.Http500": [],
  "Taco.view.storeCredit.Index": [],
  "Taco.model.ShopperNotes": [],
  "Taco.store.Behaviors": [],
  "Ext.ux.IFrame": [],
  "Taco.core.ux.OptionComboBox": [],
  "Taco.view.navigation.PrimaryMenu": [],
  "Taco.view.error.Http404": [],
  "Taco.model.ProductProperty": [],
  "Taco.model.StateComboBox": [],
  "Taco.controller.Products": [],
  "Taco.store.ProductOptionValues": [],
  "Taco.core.ux.EditContainer": [],
  "Taco.view.settings.shipping.subform.ShippingProvider": [],
  "Taco.view.option.valueEditor.MultiValue": [],
  "Taco.model.NavigationTreeNode": [],
  "Taco.view.paymentAndCheckout.FieldDescription": [],
  "Taco.store.TimeZones": [],
  "Taco.view.catalog.Index": [],
  "Taco.view.locationType.Index": [],
  "Taco.store.TaxRates": [],
  "Taco.core.ux.browser.Browsable": [],
  "Taco.controller.Message": [],
  "Taco.view.order.Header": [],
  "Taco.controller.LocationInventory": [],
  "Taco.core.EventChain": [],
  "Taco.view.pageTemplate.Index": [],
  "Taco.view.settings.paymentAndCheckout.Edit": [],
  "Ext.ux.FieldReplicator": [],
  "Taco.view.product.subform.Subform": [],
  "Taco.view.option.preview.TextField": [],
  "Taco.view.website.entityAdapters.CategoryEntityAdapter": [],
  "Taco.view.location.Edit": [],
  "Taco.view.product.subform.Extras": [],
  "Taco.model.ShippingClass": [],
  "Taco.store.Capability": [],
  "Taco.view.product.subform.SEO": [],
  "Taco.store.CustomerAccountNotes": [],
  "Ext.ux.dd.PanelFieldDragZone": [],
  "Taco.core.ux.content.Body": [],
  "Taco.core.ux.ComboFilter": [],
  "Taco.view.customers.subform.StoreCredit": [],
  "Taco.core.context.TaContext": [],
  "Taco.model.Wishlist": [],
  "Taco.core.ux.simplegrid.Body": [],
  "Taco.view.product.subform.ListExtraEditor": [],
  "Taco.store.Products": [],
  "Taco.core.ux.tinymce.TinyMCE": [],
  "Taco.shared.view.field.Address": [],
  "Taco.core.ux.form.Editor": [],
  "Taco.core.ux.form.FontPicker": [],
  "Ext.ux.GroupTabPanel": [],
  "Taco.model.Channel": [],
  "Taco.core.ux.modal.Modal": [],
  "Ext.ux.statusbar.ValidationStatus": [],
  "Taco.view.customers.subform.OrderHistory": [],
  "Taco.store.WidgetDefinitions": [],
  "Ext.ux.layout.Center": [],
  "Taco.controller.Locations": [],
  "Taco.view.settings.shipping.subform.ShippingFrom": [],
  "Taco.view.order.modal.RequestCheck": [],
  "Taco.core.ux.form.TextFieldColumn": [],
  "Taco.model.ProductExtraListItem": [],
  "Taco.model.Address": [],
  "Taco.core.ux.tab.Panel": [],
  "Taco.core.ux.CategoryComboBox": [],
  "Ext.ux.form.field.BoxSelect": [],
  "Taco.core.ux.mixins.RowEditable": [],
  "Taco.core.ux.content.Header": [],
  "Taco.core.ux.OptionValueGrid": [],
  "Taco.view.website.Index": [],
  "Taco.core.ContentView": [],
  "Taco.model.FacetSource": [],
  "Taco.view.location.inventory.LocationInventory": [],
  "Taco.core.context.Site": [],
  "Taco.controller.Attributes": [],
  "Taco.model.OrderItemDiscount": [],
  "Taco.store.CustomerGroups": [],
  "Ext.ux.event.Player": [],
  "Taco.view.settings.paymentAndCheckout.subform.CheckoutPreference": [],
  "Taco.core.ux.form.NavForm": [],
  "Taco.core.ux.modal.Mini": [],
  "Taco.view.navigation.PrimarySubMenuItem": [],
  "Taco.core.ux.action.Secondary": [],
  "Taco.model.ProductVariation": [],
  "Taco.core.ux.modal.Content": [],
  "Ext.ux.ToolbarDroppable": [],
  "Taco.model.GatewayDefinitions": [],
  "Taco.core.ux.form.BackgroundImageField": [],
  "Taco.controller.ProductTypes": [],
  "Taco.store.Channels": [],
  "Taco.overrides.form.field.Base": [],
  "Taco.view.inventory.QuantityEdit": [],
  "Taco.core.ux.form.SelectField": [],
  "Taco.store.shared.ContainerStore": [],
  "Taco.view.generalSettings.subform.Notifications": [],
  "Ext.ux.TabCloseMenu": [],
  "Taco.model.LocationInventory": [],
  "Taco.view.order.widget.UnpackagedItems": [],
  "Taco.core.ux.form.field.Container": [],
  "Taco.shared.view.field.Image": [],
  "Taco.view.themesettings.Section": [],
  "Taco.core.ux.TreeList": [],
  "Ext.ux.grid.filter.DateTimeFilter": [],
  "Taco.model.PaymentReference": [],
  "Taco.core.util.GetsTextFormat": [],
  "Taco.view.order.widget.OrderTotalPanel": [],
  "Taco.view.generalsettings.Form": [],
  "Ext.ux.grid.FiltersFeature": [],
  "Taco.core.ux.GroupedView": [],
  "Taco.core.ux.modal.SidebarModal": [],
  "Taco.view.report.Index": [],
  "Taco.view.theme.Index": [],
  "Taco.controller.Analytics": [
    "Taco.Analytics"
  ],
  "Taco.core.ux.grid.ActionColumn": [],
  "Taco.model.OrderPayment": [],
  "Taco.store.StateComboBox": [],
  "Taco.model.CheckoutSettings": [],
  "Ext.ux.grid.TransformGrid": [],
  "Taco.view.category.Modal": [],
  "Taco.core.ux.form.field.AdminUser": [],
  "Taco.overrides.menu.Item": [],
  "Taco.view.navigation.ContextSwitcherView": [],
  "Taco.core.ux.picker.DateTime": [],
  "Taco.core.ux.form.TextField": [],
  "Taco.view.generalSettings.subform.Tools": [],
  "Ext.ux.ajax.XmlSimlet": [],
  "Ext.ux.event.Driver": [],
  "Taco.view.website.settings.ProductDocument": [],
  "Taco.controller.FileManager": [],
  "Taco.controller.Dashboard": [],
  "Taco.core.ux.form.RemovableColumn": [],
  "Taco.model.PageTypeDefinition": [],
  "Taco.core.ux.CustomerGroupComboBox": [],
  "Taco.controller.SiteSelection": [],
  "Taco.controller.Settings": [],
  "Taco.core.ux.form.OnOffSliderButton": [],
  "Taco.view.order.modal.CapturePaymentManual": [],
  "Ext.ux.form.MultiSelect": [
    "Ext.ux.Multiselect"
  ],
  "Taco.model.Category": [],
  "Taco.core.ux.TabBar": [],
  "Taco.view.product.option.Modal": [],
  "Taco.core.ux.PanelDD": [],
  "Taco.core.ux.QuickAdder": [],
  "Taco.view.orderAttribute.Index": [],
  "Taco.view.generalSettings.subform.Robots": [],
  "Taco.core.ux.action.SecondaryButton": [],
  "Taco.view.customers.subform.ShippingInformation": [],
  "Taco.model.OrderSummary": [],
  "Taco.view.customers.GroupsForm": [],
  "Taco.view.location.subform.StoreHours": [],
  "Taco.core.ux.IconList": [],
  "Taco.store.StoreCredits": [],
  "Ext.ux.event.RecorderManager": [],
  "Taco.core.ux.window.Modal": [],
  "Taco.core.ux.grid.Header": [],
  "Taco.store.LocalizedStrings": [],
  "Taco.view.navigation.GlobalSearchBox": [],
  "Taco.store.SiteDirectoryNodes": [],
  "Taco.controller.Tbd": [],
  "Taco.model.SimplegridColumn": [],
  "Taco.view.order.Grid": [],
  "Taco.core.ux.browser.FilterList": [],
  "Taco.core.data.RemoteException": [],
  "Taco.model.InternationalShippingRate": [],
  "Taco.view.order.subform.Return": [],
  "Taco.model.ProductType": [],
  "Taco.view.website.widgetEditors.AddThis": [],
  "Taco.view.option.preview.RadioButtons": [],
  "Taco.view.website.WidgetEditor": [],
  "Taco.view.product.AdvancedSearchForm": [],
  "Taco.core.ux.CellEditing": [],
  "Taco.core.data.Model": [],
  "Taco.controller.StoreCredits": [],
  "Taco.shared.view.form.ExtensibleAttribute": [],
  "Ext.ux.TabScrollerMenu": [],
  "Taco.core.util.Protectable": [],
  "Taco.view.product.subform.Categories": [],
  "Taco.store.ThemeFonts": [],
  "Taco.core.ux.simplegrid.Grid": [],
  "Taco.view.category.Index": [],
  "Taco.model.NavigationItem": [],
  "Taco.model.WishlistItem": [],
  "Taco.view.settings.shipping.Edit": [],
  "Taco.model.ExtensibleAttributeValue": [],
  "Taco.controller.Catalog": [],
  "Taco.view.generalSettings.subform.AddressValidation": [],
  "Ext.ux.LiveSearchGridPanel": [],
  "Taco.store.States": [],
  "Ext.ux.grid.filter.DateFilter": [],
  "Taco.view.settings.paymentAndCheckout.subform.PaymentType": [],
  "Taco.store.Countries": [],
  "Taco.controller.WidgetDefinitions": [],
  "Taco.model.Navigation": [],
  "Taco.store.OptionComboBox": [],
  "Taco.model.CustomerGroup": [],
  "Taco.model.OrderShippingDiscount": [],
  "Ext.ux.BoxReorderer": [],
  "Taco.model.ReturnItem": [],
  "Taco.core.ux.modal.Confirmation": [],
  "Taco.view.order.widget.CreateReturnPanel": [],
  "Taco.view.product.Edit": [],
  "Taco.core.ux.form.SlugField": [],
  "Taco.core.ux.tinymce.WindowManager": [],
  "Taco.store.ProductBundlePicker": [],
  "Taco.store.ThemeListing": [],
  "Taco.model.CouponCode": [],
  "Taco.view.customers.subform.Subform": [],
  "Taco.view.order.modal.VoidPaymentManual": [],
  "Taco.view.settings.shipping.subform.Custom": [],
  "Taco.Application": [],
  "Taco.core.ux.form.Form": [],
  "Taco.view.order.modal.CapturePayment": [],
  "Taco.model.LocalizedString": [],
  "Taco.view.siteSelection.Index": [],
  "Taco.view.product.subform.CrossSale": [],
  "Taco.view.order.modal.CheckPayment": [],
  "Taco.shared.view.field.LocationPickerField": [],
  "Taco.model.ShippingCarrierSetting": [],
  "Taco.model.Location": [],
  "Taco.model.ProductOption": [],
  "Taco.view.option.TempValueEditor": [],
  "Taco.core.ux.form.FileInputButton": [],
  "Taco.core.ux.tab.Picker": [],
  "Taco.core.ux.form.EditorLayout": [],
  "Taco.view.attribute.Index": [],
  "Taco.store.LocationTypes": [],
  "Taco.core.ux.form.FullEditor": [],
  "Taco.view.storeCredit.Form": [],
  "Taco.model.CustomShippingRate": [],
  "Taco.view.theme.ThemeView": [],
  "Taco.core.util.RangeFilter": [],
  "Taco.view.image.Uploader": [],
  "Taco.view.product.option.VariationGrid": [],
  "Ext.ux.grid.filter.StringFilter": [],
  "Taco.store.WidgetInstances": [],
  "Taco.store.PackagingTypes": [],
  "Taco.view.productType.Index": [],
  "Taco.core.StateManager": [],
  "Taco.view.productType.AttributeGroup": [],
  "Taco.core.context.StoreItem": [],
  "Taco.model.ShippingMethod": [],
  "Taco.view.customerAttribute.Index": [],
  "Taco.core.ux.ComplexDataView": [],
  "Taco.core.ux.grid.RowExpander": [],
  "Taco.core.ux.form.NavForm2": [],
  "Taco.controller.PageTemplates": [],
  "Taco.view.product.Modal": [],
  "Taco.core.util.UploadManager": [],
  "Taco.view.account.Overview": [],
  "Taco.core.CTemplate": [],
  "Taco.core.ux.TextFilter": [],
  "Taco.controller.Customers": [],
  "Ext.ux.grid.menu.RangeMenu": [],
  "Taco.model.Facet": [],
  "Taco.store.OrderAttributes": [],
  "Taco.model.LocationType": [],
  "Taco.store.ConfiguredShippingRates": [],
  "Taco.view.order.subform.ShippingSimple": [],
  "Taco.view.settings.paymentAndCheckout.ExternalGateway": [],
  "Taco.core.ux.Hint": [],
  "Taco.core.util.GetsParentPage": [],
  "Taco.model.ThemeListing": [],
  "Taco.core.util.Common": [],
  "Taco.view.order.subform.Shipping": [],
  "Taco.view.customers.Form": [],
  "Taco.view.themesettings.Index": [],
  "Taco.core.ux.TabPanel": [],
  "MyReader": [],
  "Taco.view.product.subform.Inventory": [],
  "Taco.store.ShippingCarrierSettings": [],
  "Taco.view.order.widget.ProcessReturnPanel": [],
  "Taco.view.product.subform.Options": [],
  "Taco.model.CmsDocumentDraft": [],
  "Taco.view.inventory.Index": [],
  "Taco.view.order.widget.ProductConfigurator": [],
  "Taco.overrides.window.Window": [],
  "Taco.core.ux.grid.Pager": [],
  "Taco.view.orderAttribute.Form": [],
  "Taco.controller.Themesettings": [],
  "Taco.model.ProductInCatalogInfo": [],
  "Taco.controller.Website": [],
  "Taco.view.customers.subform.Information": [],
  "Taco.model.UspsSharedShippingMethod": [],
  "Ext.ux.DataTip": [],
  "Taco.model.ProductExtra": [],
  "Taco.core.ux.tab.Tab": [],
  "Ext.ux.ajax.JsonSimlet": [],
  "Taco.view.settings.paymentAndCheckout.subform.LegalInformation": [],
  "Taco.view.location.Form": [],
  "Taco.store.Roles": [],
  "Taco.shared.view.modal.Wishlist": [],
  "Taco.core.ux.form.StepContainer": [],
  "Taco.view.website.entityAdapters.BaseEntityAdapter": [],
  "Taco.model.AccountUser": [],
  "Taco.core.util.TextSelection": [],
  "Taco.view.role.Form": [],
  "Taco.view.order.modal.AddRefund": [],
  "Taco.view.order.modal.IssueCredit": [],
  "Taco.view.order.modal.AddPayment": [],
  "Taco.core.ux.ListGridToggle": [],
  "Taco.core.ux.form.ColorField": [],
  "Ext.ux.DataView.DragSelector": [],
  "Taco.core.ux.form.UnitField": [],
  "Taco.view.website.widgetEditors.FeaturedProducts": [],
  "Taco.store.UspsConfigurations": [],
  "Ext.ux.grid.menu.ListMenu": [],
  "Taco.controller.LocationTypes": [],
  "Taco.view.order.subform.Subform": [],
  "Taco.view.location.Index": [],
  "Taco.core.ux.form.field.MultiSelect": [],
  "Taco.model.Option": [],
  "Taco.view.role.Index": [],
  "Taco.view.settings.shipping.widget.RateEditor": [],
  "Taco.view.order.modal.AddPaymentManual": [],
  "Taco.store.TempPages": [],
  "Taco.view.customers.Index": [],
  "Taco.core.ux.action.PrimarySplitButton": [],
  "Taco.controller.Account": [],
  "Taco.core.Controller": [],
  "Taco.store.CustomerGroupComboBox": [],
  "Taco.model.ItemFilter": [],
  "Taco.model.CartItem": [],
  "Taco.core.ux.ComponentColumn": [],
  "Taco.store.AccountUsers": [],
  "Taco.view.settings.tax.Edit": [],
  "Taco.view.Header": [],
  "Ext.ux.PreviewPlugin": [],
  "Taco.view.email.Edit": [],
  "Taco.view.order.subform.Customer": [],
  "Ext.ux.ajax.SimXhr": [],
  "Ext.ux.CellDragDrop": [],
  "Taco.core.layout.HFlex": [],
  "Taco.view.storeCredit.Edit": [],
  "Ext.ux.SlidingPager": [],
  "Taco.view.productType.Edit": [],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.grid.filter.NumericFilter": [],
  "Taco.controller.Roles": [],
  "Taco.view.order.widget.DiscountRowBody": [],
  "Taco.view.Viewport": [],
  "Taco.store.Navigation": [],
  "Ext.ux.event.Recorder": [],
  "Taco.controller.GeneralSettings": [],
  "Taco.store.OrderNotes": [],
  "Taco.store.AdminUsers": [],
  "Taco.overrides.panel.Tool": [],
  "Ext.ux.grid.filter.BooleanFilter": [],
  "Taco.view.role.Edit": [],
  "Taco.view.navigation.PrimarySubMenu": [],
  "Taco.store.OrderItems": [],
  "Taco.model.AttributeValue": [],
  "Taco.model.Discount": [],
  "Taco.core.ux.form.Linker": [],
  "Taco.core.context.Catalog": [],
  "Ext.ux.form.SearchField": [],
  "Taco.view.product.subform.General": [],
  "Taco.core.ux.action.Button": [],
  "Taco.view.orderAttribute.Edit": [],
  "Taco.view.dashboard.Index": [],
  "Ext.ux.dd.CellFieldDropZone": [],
  "Taco.view.product.variant.Grid": [],
  "Taco.view.website.settings.EmailTemplate": [],
  "Taco.core.ux.form.FilterContainer": [],
  "Taco.model.RedirectEntry": [],
  "Taco.core.ux.window.Alert": [],
  "Taco.view.category.Edit": [],
  "Taco.view.settings.tax.Form": [],
  "Taco.store.GeneralSettings": [],
  "Taco.view.productOption.Edit": [],
  "Taco.core.ux.CellEditor": [],
  "Taco.view.customerAttribute.Edit": [],
  "Taco.core.ux.mixins.Searchable": [],
  "Taco.view.order.Edit": [],
  "Taco.core.AppState": [],
  "Taco.model.SelectedShippingMethod": [],
  "Taco.view.customers.subform.BillingInformation": [],
  "Taco.core.ux.browser.SearchList": [],
  "Ext.ux.grid.filter.ListFilter": [],
  "Taco.view.navigation.SecondaryMenu": [],
  "Taco.store.CmsDocuments": [],
  "Taco.model.TaxRate": [],
  "Taco.shared.view.modal.Address": [],
  "Taco.core.layout.Toolbar": [],
  "Taco.view.location.subform.Location": [],
  "Taco.store.ProductComboBox": [],
  "Taco.view.productType.Form": [],
  "Taco.model.BundledProduct": [],
  "Taco.core.ux.SimpleEditor": [],
  "Taco.view.option.ConfigurableEdit": [],
  "Taco.model.SiteDirectoryNode": [],
  "Taco.core.ux.action.Primary": [],
  "Taco.view.NotifierBar": [],
  "Taco.model.CustomerAccountNote": [],
  "Ext.ux.GMapPanel": [],
  "Taco.store.UspsSharedShippingMethods": [],
  "Taco.view.website.widgetEditors.HorizontalRule": [],
  "Taco.store.Attributes": [],
  "Taco.view.settings.shipping.widget.RateList": [],
  "Taco.model.TimeZone": [],
  "Taco.view.website.settings.WebDocument": [],
  "Taco.core.PageView": [],
  "Taco.core.data.ReadAheadProxy": [],
  "Taco.store.DomesticShippingRates": [],
  "Taco.view.settings.paymentAndCheckout.Form": [],
  "Taco.view.website.settings.CategoryDocument": [],
  "Taco.overrides.menu.Menu": [],
  "Taco.view.website.settings.CatalogSeo": [],
  "Taco.model.RuntimeProductSearchResult": [],
  "Taco.model.WidgetDefinition": [],
  "Ext.ux.DataView.Animated": [],
  "Taco.core.ux.ScrollSpy": [],
  "Taco.view.customers.subform.Notes": [],
  "Taco.model.Capability": [],
  "Taco.core.ux.simplegrid.Header": [],
  "Taco.view.pendingChange.Product": [],
  "Taco.controller.Orders": [],
  "Taco.view.account.Billing": [],
  "Taco.core.data.StoreManager": [],
  "Taco.core.ux.action.DirtyButton": [],
  "Ext.ux.statusbar.StatusBar": [
    "Ext.ux.StatusBar"
  ],
  "Taco.controller.Navigation": [],
  "Taco.core.ux.form.Tasks": [],
  "Taco.overrides.window.MessageBox": [],
  "Taco.view.generalSettings.subform.Analytics": [],
  "Taco.core.ux.form.TextAlignment": [],
  "Taco.core.ux.TileView": [],
  "Taco.core.ux.action.PrimaryButton": [],
  "Taco.shared.model.File": [],
  "Taco.view.email.Index": [],
  "Taco.view.product.Index": [],
  "Taco.core.ux.modal.ContentWithActions": [],
  "Taco.model.SiteShippingSettings": [],
  "Taco.model.Attribute": [],
  "Taco.view.option.preview.DropDown": [],
  "Taco.view.capability.Form": [],
  "Taco.view.product.subform.Bundle": [],
  "Taco.view.product.GlobalForm": [],
  "Taco.view.product.subform.Properties": [],
  "Taco.core.ux.GenEditor": [],
  "Ext.ux.DataView.Draggable": [],
  "Taco.view.order.modal.EditTrackingNumber": [],
  "Taco.view.order.subform.Payment": [],
  "Taco.core.ux.form.BackgroundImagePicker": [],
  "Taco.core.ux.grid.RowBody": [],
  "Taco.store.ProductExtraListItems": [],
  "Taco.view.category.Form": [],
  "Ext.ux.form.ItemSelector": [
    "Ext.ux.ItemSelector"
  ],
  "Ext.ux.Spotlight": [],
  "Taco.core.ux.grid.Panel": [],
  "Taco.view.order.modal.ProductConfigurator": [],
  "Taco.shared.view.modal.StoreCredit": [],
  "Taco.model.ProductImageDocument": [],
  "Taco.core.ux.IndentedTreeColumn": [],
  "Taco.model.Order": [],
  "Taco.core.ux.modal.Cover": [],
  "Taco.controller.PendingChanges": [],
  "Taco.model.DomesticShippingRate": [],
  "Taco.model.Country": [],
  "Taco.store.RedirectEntries": [],
  "Taco.controller.Channels": [],
  "Taco.overrides.form.Basic": [],
  "Ext.ux.ajax.DataSimlet": [],
  "Taco.model.CmsDocument": [],
  "Taco.view.order.widget.DiscountPickerField": [],
  "Taco.core.ux.form.CurrencyField": [],
  "Taco.core.ux.TilePanel": [],
  "Taco.shared.store.Files": [],
  "Taco.core.ux.form.field.EditableDisplayField": [],
  "Taco.core.ux.IconSizeSlider": [],
  "Taco.view.paymentAndCheckout.RadioList": [],
  "Taco.controller.CustomerAttributes": [],
  "Taco.store.LocationInventories": [],
  "Taco.view.option.valueEditor.TextField": [],
  "Taco.core.ux.window.Drawer": [],
  "Taco.store.SelectedShippingMethods": [],
  "Taco.view.order.modal.CreditPaymentManual": [],
  "Taco.core.ux.browser.ItemBrowser": [],
  "Taco.view.discount.Edit": [],
  "Taco.core.ux.form.Step": [],
  "Taco.model.Role": [],
  "Taco.view.testing.Shim": [],
  "Taco.overrides.form.field.ComboBox": [],
  "Taco.controller.Inventory": [],
  "Taco.view.image.UploadItem": [],
  "Taco.core.ux.HtmlEditor": [],
  "Taco.core.ux.SidebarList": [],
  "Taco.view.order.modal.EditOrderDetail": [],
  "Taco.store.CustomerGroups": [],
  "Taco.store.CustomerAttributes": [],
  "Taco.view.generalSettings.subform.About": [],
  "Taco.controller.OrderAttributes": [],
  "Taco.core.ux.form.EditorWrapper": [],
  "Taco.view.product.widget.ProductBundleGrid": [],
  "Taco.shared.view.field.Customer": [],
  "Taco.core.ux.DragSource": [],
  "Taco.core.ux.form.field.SingleImageField": [],
  "Taco.store.InternationalShippingRates": [],
  "Taco.store.Wishlists": [],
  "Taco.view.location.inventory.Index": [],
  "Taco.core.ux.form.Module": [],
  "Taco.model.TargetedShippingMethod": [],
  "Taco.core.data.AjaxProxy": [],
  "Ext.ux.ProgressBarPager": [],
  "Taco.store.CmsDocumentDrafts": [],
  "Taco.model.ProductComboBox": [],
  "Taco.locale.Strings": [],
  "Taco.view.capability.Edit": [],
  "Taco.model.Behavior": [],
  "Taco.model.Contact": [],
  "Taco.model.OrderAttribute": [],
  "Taco.view.website.settings.facets.Facets": [],
  "Taco.core.ux.FileDragDroppable": [],
  "Taco.store.Locations": [],
  "Taco.controller.Errors": [],
  "Taco.view.capability.Index": [],
  "Taco.store.ItemFilters": [],
  "Taco.core.ux.DragDropZone": [],
  "Taco.view.account.Users": [],
  "Taco.view.order.widget.OrderItemGrid": [],
  "Taco.model.CustomerAttribute": [],
  "Taco.view.discount.Form": [],
  "Taco.model.ActiveRateProvider": [],
  "Ext.ux.ajax.SimManager": [],
  "Taco.view.themesettings.Group": [],
  "Taco.core.util.ExceptionWhiner": [],
  "Taco.controller.Email": [],
  "Taco.view.order.widget.Package": [],
  "Taco.model.KeyValuePair": [],
  "Taco.model.AdminUser": [],
  "Taco.core.ux.action.GridAction": [],
  "Taco.store.GatewayDefinitions": [],
  "Taco.core.ux.form.field.PageTemplate": [],
  "Taco.store.shared.BaseStore": [],
  "Taco.view.product.option.Form": [],
  "Taco.view.channel.Index": [],
  "Taco.view.paymentAndCheckout.StandaloneAccordion": [],
  "Taco.controller.Redirects": [],
  "Taco.view.settings.shipping.subform.ShippingPreferences": [],
  "Taco.view.settings.Publishing": [],
  "Taco.core.ux.form.field.Product": [],
  "Taco.model.Product": [],
  "Taco.core.ux.form.FieldGroup": [],
  "Taco.view.settings.shipping.Form": [],
  "Taco.view.product.subform.Merchandising": [],
  "Taco.view.fileManager.Associator": [],
  "Taco.view.settings.shipping.subform.MethodsAndRates": [],
  "Taco.model.WidgetInstance": [],
  "Taco.view.product.SiteForm": [],
  "Taco.view.generalSettings.Index": [],
  "Ext.ux.TreePicker": [],
  "Taco.core.layout.VFlex": [],
  "Taco.core.ux.BoxReorderer": [],
  "Taco.view.themesettings.Addons": [],
  "Taco.view.report.SidebarList": [],
  "Ext.ux.data.PagingMemoryProxy": [
    "Ext.data.PagingMemoryProxy"
  ],
  "Taco.overrides.grid.RowEditor": [],
  "Ext.ux.grid.filter.Filter": [],
  "Taco.view.role.BehaviorsForm": [],
  "Ext.ux.GroupTabRenderer": [],
  "Taco.overrides.form.field.Display": [],
  "Taco.controller.Testing": [],
  "Taco.view.website.settings.facets.FacetRangeQueryForm": [],
  "Taco.core.ux.DragHandleColumn": [],
  "Taco.view.order.AdvancedSearchForm": [],
  "Taco.core.ux.content.Sidebar": [],
  "Taco.store.ExternalGatewayDefinitions": [],
  "Taco.core.ux.form.FontField": [],
  "Taco.view.website.entityAdapters.TemplateEntityAdapter": [],
  "Taco.overrides.grid.RowEditorButtons": [],
  "Taco.view.product.Form": [],
  "Taco.core.ux.grid.HeaderDropZone": [],
  "Taco.core.ux.action.TreeListAction": [],
  "Taco.view.product.variant.Modal": [],
  "Taco.store.ChannelPicker": [],
  "Taco.store.NavigationTreeNodes": [],
  "Taco.core.FormPanel": [],
  "Taco.model.UspsConfiguration": [],
  "Taco.model.OrderNote": [],
  "Taco.controller.Themes": [],
  "Taco.core.ux.ColorPicker": [],
  "Taco.core.data.CategoryTreeProxy": [],
  "Taco.model.Shipment": [],
  "Taco.shared.view.form.Address": [],
  "Taco.controller.Reports": [],
  "Taco.core.ux.FilterableDataView": [],
  "Taco.model.Return": [],
  "Taco.model.StoreCredit": [],
  "Taco.store.Discounts": [],
  "Taco.core.ux.MultiImageField": [],
  "Ext.ux.DataView.LabelEditor": [],
  "Taco.view.navigation.PrimaryMenuView": [],
  "Taco.core.ux.form.FlexBox": [],
  "Taco.core.ux.form.Interface": [],
  "Taco.view.website.entityAdapters.ProductEntityAdapter": [],
  "Taco.view.attribute.Form": [],
  "Taco.core.ux.form.DateTime": [],
  "Taco.store.RuntimeProductSearch": [],
  "Taco.model.RuntimeProduct": [],
  "Taco.model.AccountInformation": [],
  "Taco.model.ShippingRate": [],
  "Taco.store.TargetedShippingMethods": [],
  "Taco.store.CategoriesTree": [],
  "Taco.model.PaymentInteraction": [],
  "Taco.model.CustomerAccount": [],
  "Taco.view.website.misc.ExternalLinkEditor": [],
  "Taco.model.ThemeFont": [],
  "Ext.ux.RowExpander": [],
  "Taco.model.OptionComboBox": [],
  "Taco.view.tbd.Index": [],
  "Taco.store.Orders": [],
  "Taco.core.ux.action.Action": [],
  "Taco.view.order.Index": [],
  "Taco.shared.util.Uploadable": [],
  "Taco.controller.Discounts": [],
  "Taco.core.ux.form.ToggleGroup": [],
  "Taco.store.shared.TreeStore": [],
  "Taco.view.product.subform.OverrideForm": [],
  "Taco.view.discount.Index": [],
  "Taco.core.ux.ClassHandledDragDrop": [],
  "Taco.store.PageTypeDefinitions": [],
  "Ext.ux.event.Maker": [],
  "Taco.store.Categories": [],
  "Taco.view.website.entityAdapters.DocumentEntityAdapter": [],
  "Taco.overrides.panel.Header": [],
  "Taco.view.account.Navigation": [],
  "Taco.view.report.Header": [],
  "Taco.model.ExternalPaymentDefinition": [],
  "Taco.view.product.AddSiteContainer": [],
  "Taco.store.Customers": []
});
Ext.ClassManager.addNameAliasMappings({
  "Taco.view.redirects.Index": [],
  "Taco.view.settings.paymentAndCheckout.Gateway": [],
  "Taco.model.CustomerGroupComboBox": [],
  "Taco.core.ux.browser.BrowserPage": [
    "widget.browserpage"
  ],
  "Taco.view.testing.StandaloneOption": [],
  "Taco.view.attribute.Edit": [],
  "Taco.core.ux.action.SplitButton": [
    "widget.taco.splitbutton"
  ],
  "Taco.core.ux.CardPanel": [
    "widget.cardpanel"
  ],
  "Taco.view.website.entityAdapters.SiteTemplateEntityAdapter": [],
  "Taco.store.ProductTypes": [],
  "Taco.controller.Capability": [],
  "Taco.store.Options": [],
  "Taco.core.ux.form.field.InlinePicker": [
    "widget.taco-inlinepicker"
  ],
  "Taco.view.fileManager.Index": [
    "widget.filemanager"
  ],
  "Taco.view.order.Form": [],
  "Ext.ux.layout.component.field.BoxSelectField": [
    "layout.boxselectfield"
  ],
  "Taco.view.website.entityAdapters.EmailTemplateEntityAdapter": [],
  "Taco.view.order.widget.PaymentPanel": [],
  "Taco.core.context.MasterCatalog": [],
  "Taco.view.pendingChange.Cms": [],
  "Taco.core.ux.BaseGrid": [
    "widget.basegrid"
  ],
  "Taco.view.order.subform.Detail": [
    "widget.taco-orderdetail"
  ],
  "Taco.model.OrderItem": [],
  "Taco.view.website.settings.facets.FacetRangeQuery": [
    "widget.taco.rangequery"
  ],
  "Taco.shared.view.field.ProductPickerField": [
    "widget.taco-productpickerfield"
  ],
  "Taco.core.ux.window.Window": [
    "widget.taco-window"
  ],
  "Taco.view.customerAttribute.Form": [],
  "Taco.model.FacetSet": [],
  "Taco.view.website.settings.facets.FacetRangeQueryGroup": [
    "widget.taco.rangequerygroup"
  ],
  "Taco.core.ux.window.MessageBox": [],
  "Taco.view.productType.AttributeForm": [
    "widget.taco.producttype.attributeform"
  ],
  "Taco.view.website.settings.General": [],
  "Taco.view.website.Tree": [
    "widget.taco-website-tree"
  ],
  "Taco.view.error.Index": [],
  "Taco.core.util.FileUploadEvent": [],
  "Taco.shared.view.field.CountryField": [
    "widget.taco-countryfield"
  ],
  "Taco.model.OptionValue": [],
  "Ext.ux.ajax.Simlet": [
    "simlet.basic"
  ],
  "Taco.view.customers.Edit": [],
  "Taco.core.ux.mixins.Pageable": [],
  "Taco.core.ux.BaseCardPanel": [
    "widget.basecardpanel"
  ],
  "Taco.model.GeneralSettings": [],
  "Taco.core.ux.grid.MenuColumn": [
    "widget.taco.menucolumn"
  ],
  "Taco.model.ProductTypeAttribute": [],
  "Taco.core.ux.content.Container": [
    "widget.contentcontainer"
  ],
  "Taco.view.customers.AdvancedSearchForm": [],
  "Taco.controller.Categories": [],
  "Taco.view.order.widget.ShippingItemGrid": [],
  "Taco.model.ProductOptionValue": [],
  "Taco.view.product.subform.Shipping": [],
  "Taco.core.ux.EditPanel": [
    "widget.editpanel"
  ],
  "Taco.view.generalSettings.subform.Maintenance": [],
  "Taco.view.navigation.ContextSwitcher": [
    "taco.contextswitcher"
  ],
  "Taco.view.error.Http500": [],
  "Taco.view.storeCredit.Index": [],
  "Taco.model.ShopperNotes": [],
  "Taco.store.Behaviors": [],
  "Ext.ux.IFrame": [
    "widget.uxiframe"
  ],
  "Taco.core.ux.OptionComboBox": [
    "widget.optioncombobox"
  ],
  "Taco.view.navigation.PrimaryMenu": [],
  "Taco.view.error.Http404": [],
  "Taco.model.ProductProperty": [],
  "Taco.model.StateComboBox": [],
  "Taco.controller.Products": [],
  "Taco.store.ProductOptionValues": [],
  "Taco.core.ux.EditContainer": [
    "widget.taco-editcontainer"
  ],
  "Taco.view.settings.shipping.subform.ShippingProvider": [],
  "Taco.view.option.valueEditor.MultiValue": [
    "widget.optionvalueeditor"
  ],
  "Taco.model.NavigationTreeNode": [],
  "Taco.view.paymentAndCheckout.FieldDescription": [
    "widget.field-description"
  ],
  "Taco.store.TimeZones": [],
  "Taco.view.catalog.Index": [],
  "Taco.view.locationType.Index": [],
  "Taco.store.TaxRates": [],
  "Taco.core.ux.browser.Browsable": [],
  "Taco.controller.Message": [],
  "Taco.view.order.Header": [],
  "Taco.controller.LocationInventory": [],
  "Taco.core.EventChain": [],
  "Taco.view.pageTemplate.Index": [
    "widget.pageTemplateIndex"
  ],
  "Taco.view.settings.paymentAndCheckout.Edit": [],
  "Ext.ux.FieldReplicator": [],
  "Taco.view.product.subform.Subform": [],
  "Taco.view.option.preview.TextField": [],
  "Taco.view.website.entityAdapters.CategoryEntityAdapter": [],
  "Taco.view.location.Edit": [],
  "Taco.view.product.subform.Extras": [
    "widget.productextrasform"
  ],
  "Taco.model.ShippingClass": [],
  "Taco.store.Capability": [],
  "Taco.view.product.subform.SEO": [],
  "Taco.store.CustomerAccountNotes": [],
  "Ext.ux.dd.PanelFieldDragZone": [],
  "Taco.core.ux.content.Body": [
    "widget.contentbody"
  ],
  "Taco.core.ux.ComboFilter": [
    "widget.taco.combofilter"
  ],
  "Taco.view.customers.subform.StoreCredit": [],
  "Taco.core.context.TaContext": [],
  "Taco.model.Wishlist": [],
  "Taco.core.ux.simplegrid.Body": [
    "widget.simplegridbody"
  ],
  "Taco.view.product.subform.ListExtraEditor": [
    "widget.taco.product.listextraeditor"
  ],
  "Taco.store.Products": [],
  "Taco.core.ux.tinymce.TinyMCE": [
    "widget.tinymcefield"
  ],
  "Taco.shared.view.field.Address": [
    "widget.taco-addressfield"
  ],
  "Taco.core.ux.form.Editor": [
    "widget.formeditor"
  ],
  "Taco.core.ux.form.FontPicker": [
    "widget.fontpicker"
  ],
  "Ext.ux.GroupTabPanel": [
    "widget.grouptabpanel"
  ],
  "Taco.model.Channel": [],
  "Taco.core.ux.modal.Modal": [
    "widget.taco.modal"
  ],
  "Ext.ux.statusbar.ValidationStatus": [],
  "Taco.view.customers.subform.OrderHistory": [],
  "Taco.store.WidgetDefinitions": [],
  "Ext.ux.layout.Center": [
    "layout.ux.center"
  ],
  "Taco.controller.Locations": [],
  "Taco.view.settings.shipping.subform.ShippingFrom": [],
  "Taco.view.order.modal.RequestCheck": [],
  "Taco.core.ux.form.TextFieldColumn": [
    "widget.textfieldcolumn"
  ],
  "Taco.model.ProductExtraListItem": [],
  "Taco.model.Address": [],
  "Taco.core.ux.tab.Panel": [
    "widget.taco.tabpanel"
  ],
  "Taco.core.ux.CategoryComboBox": [
    "widget.categorycombobox"
  ],
  "Ext.ux.form.field.BoxSelect": [
    "widget.boxselect",
    "widget.comboboxselect"
  ],
  "Taco.core.ux.mixins.RowEditable": [],
  "Taco.core.ux.content.Header": [
    "widget.contentheader"
  ],
  "Taco.core.ux.OptionValueGrid": [
    "widget.optionvaluegrid"
  ],
  "Taco.view.website.Index": [],
  "Taco.core.ContentView": [
    "widget.contentview"
  ],
  "Taco.model.FacetSource": [],
  "Taco.view.location.inventory.LocationInventory": [],
  "Taco.core.context.Site": [],
  "Taco.controller.Attributes": [],
  "Taco.model.OrderItemDiscount": [],
  "Taco.store.CustomerGroups": [],
  "Ext.ux.event.Player": [],
  "Taco.view.settings.paymentAndCheckout.subform.CheckoutPreference": [],
  "Taco.core.ux.form.NavForm": [
    "widget.taco.navform"
  ],
  "Taco.core.ux.modal.Mini": [
    "widget.minimodal"
  ],
  "Taco.view.navigation.PrimarySubMenuItem": [],
  "Taco.core.ux.action.Secondary": [
    "widget.secondaryaction"
  ],
  "Taco.model.ProductVariation": [],
  "Taco.core.ux.modal.Content": [
    "widget.contentmodal"
  ],
  "Ext.ux.ToolbarDroppable": [],
  "Taco.model.GatewayDefinitions": [],
  "Taco.core.ux.form.BackgroundImageField": [
    "widget.backgroundimagefield"
  ],
  "Taco.controller.ProductTypes": [],
  "Taco.store.Channels": [],
  "Taco.overrides.form.field.Base": [],
  "Taco.view.inventory.QuantityEdit": [],
  "Taco.core.ux.form.SelectField": [
    "widget.selectfield"
  ],
  "Taco.store.shared.ContainerStore": [],
  "Taco.view.generalSettings.subform.Notifications": [],
  "Ext.ux.TabCloseMenu": [
    "plugin.tabclosemenu"
  ],
  "Taco.model.LocationInventory": [],
  "Taco.view.order.widget.UnpackagedItems": [],
  "Taco.core.ux.form.field.Container": [],
  "Taco.shared.view.field.Image": [
    "widget.taco.imagefield"
  ],
  "Taco.view.themesettings.Section": [
    "widget.themesettingssection"
  ],
  "Taco.core.ux.TreeList": [
    "widget.treelist"
  ],
  "Ext.ux.grid.filter.DateTimeFilter": [
    "gridfilter.datetime"
  ],
  "Taco.model.PaymentReference": [],
  "Taco.core.util.GetsTextFormat": [],
  "Taco.view.order.widget.OrderTotalPanel": [],
  "Taco.view.generalsettings.Form": [
    "widget.generalsettingseditor"
  ],
  "Ext.ux.grid.FiltersFeature": [
    "feature.filters"
  ],
  "Taco.core.ux.GroupedView": [],
  "Taco.core.ux.modal.SidebarModal": [
    "widget.sidebarmodal"
  ],
  "Taco.view.report.Index": [],
  "Taco.view.theme.Index": [],
  "Taco.controller.Analytics": [],
  "Taco.core.ux.grid.ActionColumn": [
    "widget.taco.actioncolumn"
  ],
  "Taco.model.OrderPayment": [],
  "Taco.store.StateComboBox": [
    "widget.statecomboboxstore"
  ],
  "Taco.model.CheckoutSettings": [],
  "Ext.ux.grid.TransformGrid": [],
  "Taco.view.category.Modal": [],
  "Taco.core.ux.form.field.AdminUser": [
    "widget.taco-adminuserfield"
  ],
  "Taco.overrides.menu.Item": [],
  "Taco.view.navigation.ContextSwitcherView": [],
  "Taco.core.ux.picker.DateTime": [
    "widget.datetimepicker"
  ],
  "Taco.core.ux.form.TextField": [
    "widget.taco.textfield"
  ],
  "Taco.view.generalSettings.subform.Tools": [],
  "Ext.ux.ajax.XmlSimlet": [
    "simlet.xml"
  ],
  "Ext.ux.event.Driver": [],
  "Taco.view.website.settings.ProductDocument": [],
  "Taco.controller.FileManager": [],
  "Taco.controller.Dashboard": [],
  "Taco.core.ux.form.RemovableColumn": [
    "widget.removablecolumn"
  ],
  "Taco.model.PageTypeDefinition": [],
  "Taco.core.ux.CustomerGroupComboBox": [
    "widget.customergroupcombobox"
  ],
  "Taco.controller.SiteSelection": [],
  "Taco.controller.Settings": [],
  "Taco.core.ux.form.OnOffSliderButton": [
    "widget.onoffsliderbutton"
  ],
  "Taco.view.order.modal.CapturePaymentManual": [],
  "Ext.ux.form.MultiSelect": [
    "widget.multiselect",
    "widget.multiselectfield"
  ],
  "Taco.model.Category": [],
  "Taco.core.ux.TabBar": [],
  "Taco.view.product.option.Modal": [],
  "Taco.core.ux.PanelDD": [],
  "Taco.core.ux.QuickAdder": [
    "widget.quickadder"
  ],
  "Taco.view.orderAttribute.Index": [],
  "Taco.view.generalSettings.subform.Robots": [],
  "Taco.core.ux.action.SecondaryButton": [
    "widget.secondarybutton"
  ],
  "Taco.view.customers.subform.ShippingInformation": [],
  "Taco.model.OrderSummary": [],
  "Taco.view.customers.GroupsForm": [],
  "Taco.view.location.subform.StoreHours": [],
  "Taco.core.ux.IconList": [
    "widget.iconlist"
  ],
  "Taco.store.StoreCredits": [],
  "Ext.ux.event.RecorderManager": [
    "widget.eventrecordermanager"
  ],
  "Taco.core.ux.window.Modal": [
    "widget.taco-modal"
  ],
  "Taco.core.ux.grid.Header": [],
  "Taco.store.LocalizedStrings": [],
  "Taco.view.navigation.GlobalSearchBox": [],
  "Taco.store.SiteDirectoryNodes": [],
  "Taco.controller.Tbd": [],
  "Taco.model.SimplegridColumn": [],
  "Taco.view.order.Grid": [],
  "Taco.core.ux.browser.FilterList": [],
  "Taco.core.data.RemoteException": [],
  "Taco.model.InternationalShippingRate": [],
  "Taco.view.order.subform.Return": [],
  "Taco.model.ProductType": [],
  "Taco.view.website.widgetEditors.AddThis": [],
  "Taco.view.option.preview.RadioButtons": [],
  "Taco.view.website.WidgetEditor": [
    "widget.taco-widgeteditor"
  ],
  "Taco.view.product.AdvancedSearchForm": [],
  "Taco.core.ux.CellEditing": [
    "plugin.tacocellediting"
  ],
  "Taco.core.data.Model": [],
  "Taco.controller.StoreCredits": [],
  "Taco.shared.view.form.ExtensibleAttribute": [
    "widget.taco.extensibleattribute.subform"
  ],
  "Ext.ux.TabScrollerMenu": [
    "plugin.tabscrollermenu"
  ],
  "Taco.core.util.Protectable": [],
  "Taco.view.product.subform.Categories": [],
  "Taco.store.ThemeFonts": [],
  "Taco.core.ux.simplegrid.Grid": [
    "widget.simplegrid"
  ],
  "Taco.view.category.Index": [],
  "Taco.model.NavigationItem": [],
  "Taco.model.WishlistItem": [],
  "Taco.view.settings.shipping.Edit": [],
  "Taco.model.ExtensibleAttributeValue": [],
  "Taco.controller.Catalog": [],
  "Taco.view.generalSettings.subform.AddressValidation": [],
  "Ext.ux.LiveSearchGridPanel": [],
  "Taco.store.States": [],
  "Ext.ux.grid.filter.DateFilter": [
    "gridfilter.date"
  ],
  "Taco.view.settings.paymentAndCheckout.subform.PaymentType": [],
  "Taco.store.Countries": [],
  "Taco.controller.WidgetDefinitions": [],
  "Taco.model.Navigation": [],
  "Taco.store.OptionComboBox": [
    "widget.optioncomboboxstore"
  ],
  "Taco.model.CustomerGroup": [],
  "Taco.model.OrderShippingDiscount": [],
  "Ext.ux.BoxReorderer": [],
  "Taco.model.ReturnItem": [],
  "Taco.core.ux.modal.Confirmation": [],
  "Taco.view.order.widget.CreateReturnPanel": [],
  "Taco.view.product.Edit": [],
  "Taco.core.ux.form.SlugField": [
    "widget.slugfield"
  ],
  "Taco.core.ux.tinymce.WindowManager": [],
  "Taco.store.ProductBundlePicker": [],
  "Taco.store.ThemeListing": [],
  "Taco.model.CouponCode": [],
  "Taco.view.customers.subform.Subform": [
    "widget.taco.customer.subform"
  ],
  "Taco.view.order.modal.VoidPaymentManual": [],
  "Taco.view.settings.shipping.subform.Custom": [],
  "Taco.Application": [],
  "Taco.core.ux.form.Form": [
    "widget.formform"
  ],
  "Taco.view.order.modal.CapturePayment": [],
  "Taco.model.LocalizedString": [],
  "Taco.view.siteSelection.Index": [],
  "Taco.view.product.subform.CrossSale": [],
  "Taco.view.order.modal.CheckPayment": [],
  "Taco.shared.view.field.LocationPickerField": [
    "widget.taco-locationpickerfield"
  ],
  "Taco.model.ShippingCarrierSetting": [],
  "Taco.model.Location": [],
  "Taco.model.ProductOption": [],
  "Taco.view.option.TempValueEditor": [
    "widget.tempoptionvalueeditor"
  ],
  "Taco.core.ux.form.FileInputButton": [
    "widget.tacofilefield"
  ],
  "Taco.core.ux.tab.Picker": [],
  "Taco.core.ux.form.EditorLayout": [],
  "Taco.view.attribute.Index": [],
  "Taco.store.LocationTypes": [],
  "Taco.core.ux.form.FullEditor": [],
  "Taco.view.storeCredit.Form": [],
  "Taco.model.CustomShippingRate": [],
  "Taco.view.theme.ThemeView": [
    "widget.widget.taco.themeview"
  ],
  "Taco.core.util.RangeFilter": [
    "widget.rangefilter"
  ],
  "Taco.view.image.Uploader": [
    "widget.imageuploader"
  ],
  "Taco.view.product.option.VariationGrid": [],
  "Ext.ux.grid.filter.StringFilter": [
    "gridfilter.string"
  ],
  "Taco.store.WidgetInstances": [],
  "Taco.store.PackagingTypes": [],
  "Taco.view.productType.Index": [
    "widget.taco.index.producttype"
  ],
  "Taco.core.StateManager": [],
  "Taco.view.productType.AttributeGroup": [
    "widget.taco.producttype.attributegroup"
  ],
  "Taco.core.context.StoreItem": [],
  "Taco.model.ShippingMethod": [],
  "Taco.view.customerAttribute.Index": [],
  "Taco.core.ux.ComplexDataView": [
    "widget.complexdataview"
  ],
  "Taco.core.ux.grid.RowExpander": [],
  "Taco.core.ux.form.NavForm2": [
    "widget.taco.navform2"
  ],
  "Taco.controller.PageTemplates": [],
  "Taco.view.product.Modal": [],
  "Taco.core.util.UploadManager": [],
  "Taco.view.account.Overview": [],
  "Taco.core.CTemplate": [],
  "Taco.core.ux.TextFilter": [
    "widget.textfilter"
  ],
  "Taco.controller.Customers": [],
  "Ext.ux.grid.menu.RangeMenu": [],
  "Taco.model.Facet": [],
  "Taco.store.OrderAttributes": [],
  "Taco.model.LocationType": [],
  "Taco.store.ConfiguredShippingRates": [],
  "Taco.view.order.subform.ShippingSimple": [
    "widget.taco-ordershippingsimple"
  ],
  "Taco.view.settings.paymentAndCheckout.ExternalGateway": [],
  "Taco.core.ux.Hint": [
    "widget.hint"
  ],
  "Taco.core.util.GetsParentPage": [],
  "Taco.model.ThemeListing": [],
  "Taco.core.util.Common": [],
  "Taco.view.order.subform.Shipping": [],
  "Taco.view.customers.Form": [],
  "Taco.view.themesettings.Index": [
    "widget.themesettingseditor"
  ],
  "Taco.core.ux.TabPanel": [
    "widget.tacotabpanel"
  ],
  "MyReader": [
    "reader.my-json"
  ],
  "Taco.view.product.subform.Inventory": [],
  "Taco.store.ShippingCarrierSettings": [],
  "Taco.view.order.widget.ProcessReturnPanel": [],
  "Taco.view.product.subform.Options": [],
  "Taco.model.CmsDocumentDraft": [],
  "Taco.view.inventory.Index": [
    "widget.inventoryindex"
  ],
  "Taco.view.order.widget.ProductConfigurator": [],
  "Taco.overrides.window.Window": [],
  "Taco.core.ux.grid.Pager": [
    "widget.taco.pager"
  ],
  "Taco.view.orderAttribute.Form": [],
  "Taco.controller.Themesettings": [],
  "Taco.model.ProductInCatalogInfo": [],
  "Taco.controller.Website": [],
  "Taco.view.customers.subform.Information": [],
  "Taco.model.UspsSharedShippingMethod": [],
  "Ext.ux.DataTip": [
    "plugin.datatip"
  ],
  "Taco.model.ProductExtra": [],
  "Taco.core.ux.tab.Tab": [
    "widget.formtab"
  ],
  "Ext.ux.ajax.JsonSimlet": [
    "simlet.json"
  ],
  "Taco.view.settings.paymentAndCheckout.subform.LegalInformation": [],
  "Taco.view.location.Form": [],
  "Taco.store.Roles": [],
  "Taco.shared.view.modal.Wishlist": [],
  "Taco.core.ux.form.StepContainer": [
    "widget.formstepcontainer"
  ],
  "Taco.view.website.entityAdapters.BaseEntityAdapter": [],
  "Taco.model.AccountUser": [],
  "Taco.core.util.TextSelection": [],
  "Taco.view.role.Form": [],
  "Taco.view.order.modal.AddRefund": [],
  "Taco.view.order.modal.IssueCredit": [],
  "Taco.view.order.modal.AddPayment": [],
  "Taco.core.ux.ListGridToggle": [
    "widget.listgridtoggle"
  ],
  "Taco.core.ux.form.ColorField": [
    "widget.colorfield"
  ],
  "Ext.ux.DataView.DragSelector": [],
  "Taco.core.ux.form.UnitField": [
    "widget.unitfield"
  ],
  "Taco.view.website.widgetEditors.FeaturedProducts": [],
  "Taco.store.UspsConfigurations": [],
  "Ext.ux.grid.menu.ListMenu": [],
  "Taco.controller.LocationTypes": [],
  "Taco.view.order.subform.Subform": [
    "widget.taco.order.subform"
  ],
  "Taco.view.location.Index": [],
  "Taco.core.ux.form.field.MultiSelect": [
    "widget.taco.field.multiselect"
  ],
  "Taco.model.Option": [],
  "Taco.view.role.Index": [],
  "Taco.view.settings.shipping.widget.RateEditor": [],
  "Taco.view.order.modal.AddPaymentManual": [],
  "Taco.store.TempPages": [],
  "Taco.view.customers.Index": [
    "widget.taco.index.customer"
  ],
  "Taco.core.ux.action.PrimarySplitButton": [
    "widget.primarysplitbutton"
  ],
  "Taco.controller.Account": [],
  "Taco.core.Controller": [],
  "Taco.store.CustomerGroupComboBox": [],
  "Taco.model.ItemFilter": [],
  "Taco.model.CartItem": [],
  "Taco.core.ux.ComponentColumn": [
    "widget.componentcolumn"
  ],
  "Taco.store.AccountUsers": [],
  "Taco.view.settings.tax.Edit": [],
  "Taco.view.Header": [],
  "Ext.ux.PreviewPlugin": [
    "plugin.preview"
  ],
  "Taco.view.email.Edit": [],
  "Taco.view.order.subform.Customer": [
    "widget.taco-ordercustomer"
  ],
  "Ext.ux.ajax.SimXhr": [],
  "Ext.ux.CellDragDrop": [
    "plugin.celldragdrop"
  ],
  "Taco.core.layout.HFlex": [
    "layout.hflex"
  ],
  "Taco.view.storeCredit.Edit": [],
  "Ext.ux.SlidingPager": [],
  "Taco.view.productType.Edit": [],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.grid.filter.NumericFilter": [
    "gridfilter.numeric"
  ],
  "Taco.controller.Roles": [],
  "Taco.view.order.widget.DiscountRowBody": [
    "feature.discountrowbody"
  ],
  "Taco.view.Viewport": [],
  "Taco.store.Navigation": [],
  "Ext.ux.event.Recorder": [],
  "Taco.controller.GeneralSettings": [],
  "Taco.store.OrderNotes": [],
  "Taco.store.AdminUsers": [],
  "Taco.overrides.panel.Tool": [],
  "Ext.ux.grid.filter.BooleanFilter": [
    "gridfilter.boolean"
  ],
  "Taco.view.role.Edit": [
    "widget.rolefulledit"
  ],
  "Taco.view.navigation.PrimarySubMenu": [],
  "Taco.store.OrderItems": [],
  "Taco.model.AttributeValue": [],
  "Taco.model.Discount": [],
  "Taco.core.ux.form.Linker": [
    "widget.linker"
  ],
  "Taco.core.context.Catalog": [],
  "Ext.ux.form.SearchField": [
    "widget.searchfield"
  ],
  "Taco.view.product.subform.General": [],
  "Taco.core.ux.action.Button": [
    "widget.taco.button"
  ],
  "Taco.view.orderAttribute.Edit": [],
  "Taco.view.dashboard.Index": [],
  "Ext.ux.dd.CellFieldDropZone": [],
  "Taco.view.product.variant.Grid": [
    "widget.taco-product-variant-grid"
  ],
  "Taco.view.website.settings.EmailTemplate": [],
  "Taco.core.ux.form.FilterContainer": [
    "widget.taco-filtercontainer"
  ],
  "Taco.model.RedirectEntry": [],
  "Taco.core.ux.window.Alert": [],
  "Taco.view.category.Edit": [
    "widget.categoryfulledit"
  ],
  "Taco.view.settings.tax.Form": [],
  "Taco.store.GeneralSettings": [],
  "Taco.view.productOption.Edit": [
    "widget.productOptionedit"
  ],
  "Taco.core.ux.CellEditor": [
    "plugin.tacocelleditor"
  ],
  "Taco.view.customerAttribute.Edit": [],
  "Taco.core.ux.mixins.Searchable": [],
  "Taco.view.order.Edit": [],
  "Taco.core.AppState": [],
  "Taco.model.SelectedShippingMethod": [],
  "Taco.view.customers.subform.BillingInformation": [],
  "Taco.core.ux.browser.SearchList": [
    "widget.searchlist"
  ],
  "Ext.ux.grid.filter.ListFilter": [
    "gridfilter.list"
  ],
  "Taco.view.navigation.SecondaryMenu": [
    "widget.secondarymenu"
  ],
  "Taco.store.CmsDocuments": [],
  "Taco.model.TaxRate": [],
  "Taco.shared.view.modal.Address": [],
  "Taco.core.layout.Toolbar": [],
  "Taco.view.location.subform.Location": [],
  "Taco.store.ProductComboBox": [],
  "Taco.view.productType.Form": [],
  "Taco.model.BundledProduct": [],
  "Taco.core.ux.SimpleEditor": [
    "widget.simpleeditor"
  ],
  "Taco.view.option.ConfigurableEdit": [
    "widget.configurableoptionedit"
  ],
  "Taco.model.SiteDirectoryNode": [],
  "Taco.core.ux.action.Primary": [
    "widget.primaryaction"
  ],
  "Taco.view.NotifierBar": [
    "widget.notifierbar"
  ],
  "Taco.model.CustomerAccountNote": [],
  "Ext.ux.GMapPanel": [
    "widget.gmappanel"
  ],
  "Taco.store.UspsSharedShippingMethods": [],
  "Taco.view.website.widgetEditors.HorizontalRule": [
    "widget.taco-horizontalrule-widgeteditor"
  ],
  "Taco.store.Attributes": [],
  "Taco.view.settings.shipping.widget.RateList": [],
  "Taco.model.TimeZone": [],
  "Taco.view.website.settings.WebDocument": [],
  "Taco.core.PageView": [],
  "Taco.core.data.ReadAheadProxy": [
    "proxy.readahead"
  ],
  "Taco.store.DomesticShippingRates": [],
  "Taco.view.settings.paymentAndCheckout.Form": [],
  "Taco.view.website.settings.CategoryDocument": [],
  "Taco.overrides.menu.Menu": [],
  "Taco.view.website.settings.CatalogSeo": [],
  "Taco.model.RuntimeProductSearchResult": [],
  "Taco.model.WidgetDefinition": [],
  "Ext.ux.DataView.Animated": [],
  "Taco.core.ux.ScrollSpy": [],
  "Taco.view.customers.subform.Notes": [],
  "Taco.model.Capability": [],
  "Taco.core.ux.simplegrid.Header": [
    "widget.simplegridheader"
  ],
  "Taco.view.pendingChange.Product": [],
  "Taco.controller.Orders": [],
  "Taco.view.account.Billing": [],
  "Taco.core.data.StoreManager": [],
  "Taco.core.ux.action.DirtyButton": [
    "widget.dirtybutton"
  ],
  "Ext.ux.statusbar.StatusBar": [
    "widget.statusbar"
  ],
  "Taco.controller.Navigation": [],
  "Taco.core.ux.form.Tasks": [],
  "Taco.overrides.window.MessageBox": [],
  "Taco.view.generalSettings.subform.Analytics": [],
  "Taco.core.ux.form.TextAlignment": [
    "widget.alignfield"
  ],
  "Taco.core.ux.TileView": [
    "widget.tileview"
  ],
  "Taco.core.ux.action.PrimaryButton": [
    "widget.primarybutton"
  ],
  "Taco.shared.model.File": [],
  "Taco.view.email.Index": [],
  "Taco.view.product.Index": [
    "widget.prodindex"
  ],
  "Taco.core.ux.modal.ContentWithActions": [
    "widget.selectormodal"
  ],
  "Taco.model.SiteShippingSettings": [],
  "Taco.model.Attribute": [],
  "Taco.view.option.preview.DropDown": [],
  "Taco.view.capability.Form": [],
  "Taco.view.product.subform.Bundle": [],
  "Taco.view.product.GlobalForm": [
    "widget.productglobalform"
  ],
  "Taco.view.product.subform.Properties": [
    "widget.productpropertiesform"
  ],
  "Taco.core.ux.GenEditor": [],
  "Ext.ux.DataView.Draggable": [],
  "Taco.view.order.modal.EditTrackingNumber": [],
  "Taco.view.order.subform.Payment": [],
  "Taco.core.ux.form.BackgroundImagePicker": [
    "widget.backgroundimagepicker"
  ],
  "Taco.core.ux.grid.RowBody": [
    "feature.taco.rowbody"
  ],
  "Taco.store.ProductExtraListItems": [],
  "Taco.view.category.Form": [],
  "Ext.ux.form.ItemSelector": [
    "widget.itemselector",
    "widget.itemselectorfield"
  ],
  "Ext.ux.Spotlight": [],
  "Taco.core.ux.grid.Panel": [
    "widget.taco.gridpanel"
  ],
  "Taco.view.order.modal.ProductConfigurator": [],
  "Taco.shared.view.modal.StoreCredit": [],
  "Taco.model.ProductImageDocument": [],
  "Taco.core.ux.IndentedTreeColumn": [
    "widget.indentedtreecolumn"
  ],
  "Taco.model.Order": [],
  "Taco.core.ux.modal.Cover": [],
  "Taco.controller.PendingChanges": [],
  "Taco.model.DomesticShippingRate": [],
  "Taco.model.Country": [],
  "Taco.store.RedirectEntries": [],
  "Taco.controller.Channels": [],
  "Taco.overrides.form.Basic": [],
  "Ext.ux.ajax.DataSimlet": [],
  "Taco.model.CmsDocument": [],
  "Taco.view.order.widget.DiscountPickerField": [],
  "Taco.core.ux.form.CurrencyField": [
    "widget.currencyfield"
  ],
  "Taco.core.ux.TilePanel": [
    "widget.tilepanel"
  ],
  "Taco.shared.store.Files": [],
  "Taco.core.ux.form.field.EditableDisplayField": [
    "widget.editabledisplayfield"
  ],
  "Taco.core.ux.IconSizeSlider": [
    "widget.iconsizeslider"
  ],
  "Taco.view.paymentAndCheckout.RadioList": [
    "widget.radiolist"
  ],
  "Taco.controller.CustomerAttributes": [],
  "Taco.store.LocationInventories": [],
  "Taco.view.option.valueEditor.TextField": [
    "widget.optionvaluetext"
  ],
  "Taco.core.ux.window.Drawer": [
    "widget.taco-drawer"
  ],
  "Taco.store.SelectedShippingMethods": [],
  "Taco.view.order.modal.CreditPaymentManual": [],
  "Taco.core.ux.browser.ItemBrowser": [
    "widget.itembrowser"
  ],
  "Taco.view.discount.Edit": [],
  "Taco.core.ux.form.Step": [
    "widget.formstep"
  ],
  "Taco.model.Role": [],
  "Taco.view.testing.Shim": [],
  "Taco.overrides.form.field.ComboBox": [],
  "Taco.controller.Inventory": [],
  "Taco.view.image.UploadItem": [
    "widget.uploaditem"
  ],
  "Taco.core.ux.HtmlEditor": [
    "widget.tacohtmleditor"
  ],
  "Taco.core.ux.SidebarList": [
    "widget.sidebarlist"
  ],
  "Taco.view.order.modal.EditOrderDetail": [],
  "Taco.store.CustomerGroups": [],
  "Taco.store.CustomerAttributes": [],
  "Taco.view.generalSettings.subform.About": [],
  "Taco.controller.OrderAttributes": [],
  "Taco.core.ux.form.EditorWrapper": [],
  "Taco.view.product.widget.ProductBundleGrid": [
    "widget.productbundlegrid"
  ],
  "Taco.shared.view.field.Customer": [
    "widget.taco-customerfield"
  ],
  "Taco.core.ux.DragSource": [],
  "Taco.core.ux.form.field.SingleImageField": [
    "widget.taco-singleimagefield"
  ],
  "Taco.store.InternationalShippingRates": [],
  "Taco.store.Wishlists": [],
  "Taco.view.location.inventory.Index": [],
  "Taco.core.ux.form.Module": [
    "widget.formmodule"
  ],
  "Taco.model.TargetedShippingMethod": [],
  "Taco.core.data.AjaxProxy": [
    "proxy.ajaxproxy"
  ],
  "Ext.ux.ProgressBarPager": [],
  "Taco.store.CmsDocumentDrafts": [],
  "Taco.model.ProductComboBox": [],
  "Taco.locale.Strings": [],
  "Taco.view.capability.Edit": [],
  "Taco.model.Behavior": [],
  "Taco.model.Contact": [],
  "Taco.model.OrderAttribute": [],
  "Taco.view.website.settings.facets.Facets": [],
  "Taco.core.ux.FileDragDroppable": [],
  "Taco.store.Locations": [],
  "Taco.controller.Errors": [],
  "Taco.view.capability.Index": [],
  "Taco.store.ItemFilters": [],
  "Taco.core.ux.DragDropZone": [
    "widget.dragdropzone"
  ],
  "Taco.view.account.Users": [],
  "Taco.view.order.widget.OrderItemGrid": [],
  "Taco.model.CustomerAttribute": [],
  "Taco.view.discount.Form": [],
  "Taco.model.ActiveRateProvider": [],
  "Ext.ux.ajax.SimManager": [],
  "Taco.view.themesettings.Group": [
    "widget.themesettingsgroup"
  ],
  "Taco.core.util.ExceptionWhiner": [],
  "Taco.controller.Email": [],
  "Taco.view.order.widget.Package": [],
  "Taco.model.KeyValuePair": [],
  "Taco.model.AdminUser": [],
  "Taco.core.ux.action.GridAction": [
    "widget.gridaction"
  ],
  "Taco.store.GatewayDefinitions": [],
  "Taco.core.ux.form.field.PageTemplate": [
    "widget.taco.field.pagetemplate"
  ],
  "Taco.store.shared.BaseStore": [],
  "Taco.view.product.option.Form": [
    "widget.optionproductform"
  ],
  "Taco.view.channel.Index": [],
  "Taco.view.paymentAndCheckout.StandaloneAccordion": [
    "widget.standalone-accordion"
  ],
  "Taco.controller.Redirects": [],
  "Taco.view.settings.shipping.subform.ShippingPreferences": [],
  "Taco.view.settings.Publishing": [],
  "Taco.core.ux.form.field.Product": [
    "widget.taco-productfield",
    "widget.taco.field.product"
  ],
  "Taco.model.Product": [],
  "Taco.core.ux.form.FieldGroup": [],
  "Taco.view.settings.shipping.Form": [],
  "Taco.view.product.subform.Merchandising": [],
  "Taco.view.fileManager.Associator": [],
  "Taco.view.settings.shipping.subform.MethodsAndRates": [],
  "Taco.model.WidgetInstance": [],
  "Taco.view.product.SiteForm": [
    "widget.productsiteform"
  ],
  "Taco.view.generalSettings.Index": [],
  "Ext.ux.TreePicker": [
    "widget.treepicker"
  ],
  "Taco.core.layout.VFlex": [
    "layout.vflex"
  ],
  "Taco.core.ux.BoxReorderer": [],
  "Taco.view.themesettings.Addons": [],
  "Taco.view.report.SidebarList": [],
  "Ext.ux.data.PagingMemoryProxy": [
    "proxy.pagingmemory"
  ],
  "Taco.overrides.grid.RowEditor": [],
  "Ext.ux.grid.filter.Filter": [],
  "Taco.view.role.BehaviorsForm": [],
  "Ext.ux.GroupTabRenderer": [
    "plugin.grouptabrenderer"
  ],
  "Taco.overrides.form.field.Display": [],
  "Taco.controller.Testing": [],
  "Taco.view.website.settings.facets.FacetRangeQueryForm": [
    "widget.taco.rangequeryform"
  ],
  "Taco.core.ux.DragHandleColumn": [
    "widget.draghandlecolumn"
  ],
  "Taco.view.order.AdvancedSearchForm": [],
  "Taco.core.ux.content.Sidebar": [
    "widget.sidebar"
  ],
  "Taco.store.ExternalGatewayDefinitions": [],
  "Taco.core.ux.form.FontField": [
    "widget.fontfield"
  ],
  "Taco.view.website.entityAdapters.TemplateEntityAdapter": [],
  "Taco.overrides.grid.RowEditorButtons": [],
  "Taco.view.product.Form": [],
  "Taco.core.ux.grid.HeaderDropZone": [],
  "Taco.core.ux.action.TreeListAction": [
    "widget.treelistaction"
  ],
  "Taco.view.product.variant.Modal": [],
  "Taco.store.ChannelPicker": [],
  "Taco.store.NavigationTreeNodes": [],
  "Taco.core.FormPanel": [
    "widget.formpanel"
  ],
  "Taco.model.UspsConfiguration": [],
  "Taco.model.OrderNote": [],
  "Taco.controller.Themes": [],
  "Taco.core.ux.ColorPicker": [],
  "Taco.core.data.CategoryTreeProxy": [
    "proxy.categorytree"
  ],
  "Taco.model.Shipment": [],
  "Taco.shared.view.form.Address": [
    "widget.taco-addressform"
  ],
  "Taco.controller.Reports": [],
  "Taco.core.ux.FilterableDataView": [
    "widget.filterabledataview"
  ],
  "Taco.model.Return": [],
  "Taco.model.StoreCredit": [],
  "Taco.store.Discounts": [],
  "Taco.core.ux.MultiImageField": [
    "widget.multiimagefield"
  ],
  "Ext.ux.DataView.LabelEditor": [],
  "Taco.view.navigation.PrimaryMenuView": [],
  "Taco.core.ux.form.FlexBox": [
    "layout.formflexbox",
    "widget.formflexbox"
  ],
  "Taco.core.ux.form.Interface": [],
  "Taco.view.website.entityAdapters.ProductEntityAdapter": [],
  "Taco.view.attribute.Form": [],
  "Taco.core.ux.form.DateTime": [
    "widget.datetime"
  ],
  "Taco.store.RuntimeProductSearch": [],
  "Taco.model.RuntimeProduct": [],
  "Taco.model.AccountInformation": [],
  "Taco.model.ShippingRate": [],
  "Taco.store.TargetedShippingMethods": [],
  "Taco.store.CategoriesTree": [],
  "Taco.model.PaymentInteraction": [],
  "Taco.model.CustomerAccount": [],
  "Taco.view.website.misc.ExternalLinkEditor": [],
  "Taco.model.ThemeFont": [],
  "Ext.ux.RowExpander": [
    "plugin.rowexpander"
  ],
  "Taco.model.OptionComboBox": [],
  "Taco.view.tbd.Index": [],
  "Taco.store.Orders": [],
  "Taco.core.ux.action.Action": [
    "widget.action"
  ],
  "Taco.view.order.Index": [
    "widget.orderindex"
  ],
  "Taco.shared.util.Uploadable": [],
  "Taco.controller.Discounts": [],
  "Taco.core.ux.form.ToggleGroup": [
    "widget.togglegroup"
  ],
  "Taco.store.shared.TreeStore": [],
  "Taco.view.product.subform.OverrideForm": [
    "widget.productoverride"
  ],
  "Taco.view.discount.Index": [
    "widget.discountlist"
  ],
  "Taco.core.ux.ClassHandledDragDrop": [
    "plugin.classhandleddragdrop"
  ],
  "Taco.store.PageTypeDefinitions": [],
  "Ext.ux.event.Maker": [],
  "Taco.store.Categories": [],
  "Taco.view.website.entityAdapters.DocumentEntityAdapter": [],
  "Taco.overrides.panel.Header": [],
  "Taco.view.account.Navigation": [],
  "Taco.view.report.Header": [],
  "Taco.model.ExternalPaymentDefinition": [],
  "Taco.view.product.AddSiteContainer": [],
  "Taco.store.Customers": []
});
