
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  "Taco.view.productOption.Edit": "app/view/productOption/edit.js",
  "Taco.view.pageTemplates.Edit": "app/view/pageTemplate/Edit.js",
  "Ext.ux.IFrame": "ux/IFrame.js",
  "Taco.store.OrderItems": "app/store/CartItems.js",
  "Taco.core.CTemplate": "app/core/util/CTemplate.js",
  "Ext.rtl.EventObjectImpl": "ext/src/rtl/EventObject.js",
  "Taco.shared.model": "app/model",
  "Ext.ux.form.SearchField": "ext/src/ux/form/SearchField.js",
  "Ext.ux.RowExpander": "ux/RowExpander.js",
  "Taco.Application": "app/application.js",
  "Taco.shared.model.File": "app/shared/model/File.js",
  "Taco.view.themesettings.Section": "app/view/themeSettings/Section.js",
  " Ext.Msg": "ext/src/window/MessageBox.js",
  "Ext.ux.form": "ux/form",
  "Ext": "ext/src",
  "Taco": "app",
  "Ext.ux.layout.component.field.BoxSelectField": "ux/form/field/BoxSelect.js",
  "Taco.view.themesettings.Index": "app/view/themeSettings/Index.js",
  "Taco.view.generalsettings.Form": "app/view/generalSettings/Form.js",
  "Taco.view.themesettings.Group": "app/view/themeSettings/Group.js",
  "Taco.core.data.AjaxProxy": "app/core/AjaxProxy.js"
});
Ext.ClassManager.addNameAlternateMappings({
  "Taco.view.settings.paymentAndCheckout.Gateway": [],
  "Taco.view.option.EditModal": [],
  "Taco.model.CustomerGroupComboBox": [],
  "Taco.core.ux.window.WindowWithActions": [],
  "Taco.core.ux.browser.BrowserPage": [],
  "Taco.view.testing.StandaloneOption": [],
  "Taco.view.attribute.Edit": [],
  "Taco.core.ux.action.SplitButton": [],
  "Taco.view.site.page.inlineeditors.InlineHtml": [],
  "Taco.core.ux.CardPanel": [],
  "Taco.view.site.CreateModal": [],
  "Taco.view.site.page.FacetRangeQueryForm": [],
  "Taco.store.ProductTypes": [],
  "Taco.store.Options": [],
  "Taco.model.User": [],
  "Taco.view.fileManager.Index": [],
  "Ext.ux.layout.component.field.BoxSelectField": [],
  "Taco.view.site.page.settings.Templates": [],
  "Taco.view.site.page.SiteDirectory": [],
  "Taco.view.site.widget.JasonImage": [],
  "Taco.view.order.widget.PaymentPanel": [],
  "Taco.core.ux.modal.BrowserModal": [],
  "Taco.core.ux.BaseGrid": [],
  "Taco.model.IpRange": [],
  "Taco.view.order.subform.Detail": [],
  "Taco.model.OrderItem": [],
  "Taco.core.ux.window.Window": [],
  "Taco.model.FacetSet": [],
  "Taco.view.site.widget.ColumnDivider": [],
  "Taco.view.productType.AttributeForm": [],
  "Taco.view.error.Index": [],
  "Taco.core.util.FileUploadEvent": [],
  "Taco.view.pageTemplates.Edit": [],
  "Taco.view.customers.Edit": [],
  "Ext.ux.ajax.Simlet": [],
  "Taco.model.OptionValue": [],
  "Taco.view.site.navigation.Tree": [],
  "Taco.core.ux.BaseCardPanel": [],
  "Taco.model.GeneralSettings": [],
  "Taco.core.ux.grid.MenuColumn": [],
  "Taco.model.ProductTypeAttribute": [],
  "Taco.view.customers.SearchForm": [],
  "Taco.core.ux.content.Container": [],
  "Taco.controller.Categories": [],
  "Taco.view.site.page.FacetRangeQueryGroup": [],
  "Taco.model.ProductOptionValue": [],
  "Taco.view.product.subform.Shipping": [],
  "Taco.core.ux.EditPanel": [],
  "Taco.view.generalSettings.subform.Maintenance": [],
  "Taco.view.navigation.ContextSwitcher": [],
  "Taco.view.error.Http500": [],
  "Taco.model.ShopperNotes": [],
  "Taco.store.Behaviors": [],
  "Ext.ux.IFrame": [],
  "Taco.core.ux.OptionComboBox": [],
  "Taco.view.navigation.PrimaryMenu": [],
  "Taco.view.error.Http404": [],
  "Taco.model.ProductProperty": [],
  "Taco.model.StateComboBox": [],
  "Taco.view.pendingchange.Cms": [],
  "Taco.view.site.page.settings.Facets": [],
  "Taco.controller.Products": [],
  "Taco.store.ProductOptionValues": [],
  "Taco.core.ux.EditContainer": [],
  "Taco.view.settings.shipping.subform.ShippingProvider": [],
  "Taco.view.option.valueEditor.MultiValue": [],
  "Taco.model.NavigationTreeNode": [],
  "Taco.view.paymentAndCheckout.FieldDescription": [],
  "Taco.store.TimeZones": [],
  "Taco.view.catalog.Index": [],
  "Taco.store.TaxRates": [],
  "Taco.core.ux.browser.Browsable": [],
  "Taco.controller.Message": [],
  "Taco.view.order.Header": [],
  "Taco.view.pageTemplate.Index": [],
  "Taco.core.EventChain": [],
  "Taco.view.settings.paymentAndCheckout.Edit": [],
  "Taco.view.product.subform.Subform": [],
  "Ext.ux.FieldReplicator": [],
  "Taco.view.option.preview.TextField": [],
  "Taco.view.product.subform.Extras": [],
  "Taco.model.ShippingClass": [],
  "Taco.view.order.modal.Address": [],
  "Taco.view.product.subform.SEO": [],
  "Taco.store.CustomerAccountNotes": [],
  "Ext.ux.dd.PanelFieldDragZone": [],
  "Taco.core.ux.content.Body": [],
  "Taco.core.ux.ComboFilter": [],
  "Taco.core.context.TaContext": [],
  "Taco.view.site.widget.ImagesGallery": [],
  "Taco.core.ux.simplegrid.Body": [],
  "Taco.view.product.subform.ListExtraEditor": [],
  "Taco.store.Products": [],
  "Taco.core.ux.tinymce.TinyMCE": [],
  "Taco.core.ux.form.Editor": [],
  "Taco.core.ux.form.FontPicker": [],
  "Ext.ux.GroupTabPanel": [],
  "Taco.core.ux.modal.Modal": [],
  "Ext.ux.statusbar.ValidationStatus": [],
  "Ext.ux.layout.Center": [],
  "Taco.store.WidgetDefinitions": [],
  "Taco.view.settings.shipping.subform.ShippingFrom": [],
  "Taco.view.order.modal.RequestCheck": [],
  "Taco.core.ux.form.TextFieldColumn": [],
  "Taco.model.ProductExtraListItem": [],
  "Taco.model.Address": [],
  "Taco.core.ux.tab.Panel": [],
  "Taco.core.ux.CategoryComboBox": [],
  "Ext.ux.form.field.BoxSelect": [],
  "Taco.view.paymentAndCheckout.Index": [],
  "Taco.core.ux.form.field.Base": [],
  "Taco.core.ux.content.Header": [],
  "Taco.core.ux.OptionValueGrid": [],
  "Taco.core.ContentView": [],
  "Taco.model.FacetSource": [],
  "Taco.core.context.Site": [],
  "Taco.controller.Attributes": [],
  "Taco.view.site.page.entityAdapters.DocumentEntityAdapter": [],
  "Taco.model.OrderItemDiscount": [],
  "Taco.store.CustomerGroups": [],
  "Ext.ux.event.Player": [],
  "Taco.view.settings.paymentAndCheckout.subform.CheckoutPreference": [],
  "Taco.core.ux.form.NavForm": [],
  "Taco.core.ux.modal.Mini": [],
  "Taco.view.navigation.PrimarySubMenuItem": [],
  "Taco.model.ProductVariation": [],
  "Taco.core.ux.action.Secondary": [],
  "Taco.view.site.page.inlineeditors.InlineImage": [],
  "Taco.model.OrderPaymentInteraction": [],
  "Taco.core.ux.modal.Content": [],
  "Ext.ux.ToolbarDroppable": [],
  "Taco.model.GatewayDefinitions": [],
  "Taco.core.ux.form.BackgroundImageField": [],
  "Taco.controller.ProductTypes": [],
  "Taco.view.inventory.QuantityEdit": [],
  "Taco.core.ux.form.SelectField": [],
  "Taco.store.shared.ContainerStore": [],
  "Taco.view.generalSettings.subform.Notifications": [],
  "Ext.ux.TabCloseMenu": [],
  "Taco.view.order.widget.UnpackagedItems": [],
  "Taco.core.ux.form.field.Container": [],
  "Taco.shared.view.field.Image": [],
  "Taco.view.themesettings.Section": [],
  "Taco.core.ux.TreeList": [],
  "Ext.ux.grid.filter.DateTimeFilter": [],
  "Taco.model.PaymentReference": [],
  "Taco.core.util.GetsTextFormat": [],
  "Taco.view.site.navigation.Themes": [],
  "Taco.view.generalsettings.Form": [],
  "Ext.ux.grid.FiltersFeature": [],
  "Taco.core.ux.GroupedView": [],
  "Taco.view.Main": [],
  "Taco.core.ux.modal.SidebarModal": [],
  "Taco.view.site.page.settings.General": [],
  "Taco.view.theme.Index": [],
  "Taco.view.address.ModalEditor": [],
  "Taco.controller.Analytics": [
    "Taco.Analytics"
  ],
  "Taco.view.site.page.FacetRangeQuery": [],
  "Taco.model.OrderPayment": [],
  "Taco.store.StateComboBox": [],
  "Ext.ux.grid.TransformGrid": [],
  "Taco.view.category.Modal": [],
  "Taco.view.site.page.hint.Widget": [],
  "Taco.view.navigation.ContextSwitcherView": [],
  "Taco.core.ux.picker.DateTime": [],
  "Taco.core.ux.form.TextField": [],
  "Taco.view.site.page.Shim": [],
  "Taco.view.generalSettings.subform.Tools": [],
  "Ext.ux.event.Driver": [],
  "Ext.ux.ajax.XmlSimlet": [],
  "Taco.controller.FileManager": [],
  "Taco.controller.Dashboard": [],
  "Taco.core.ux.form.RemovableColumn": [],
  "Taco.model.PageTypeDefinition": [],
  "Taco.core.ux.CustomerGroupComboBox": [],
  "Taco.controller.Settings": [],
  "Taco.core.ux.form.OnOffSliderButton": [],
  "Taco.model.Category": [],
  "Ext.ux.form.MultiSelect": [
    "Ext.ux.Multiselect"
  ],
  "Taco.core.ux.TabBar": [],
  "Taco.view.product.option.Modal": [],
  "Taco.core.ux.PanelDD": [],
  "Taco.core.ux.QuickAdder": [],
  "Taco.view.generalSettings.subform.Robots": [],
  "Taco.core.ux.action.SecondaryButton": [],
  "Taco.model.OrderSummary": [],
  "Taco.view.customers.GroupsForm": [],
  "Taco.core.ux.IconList": [],
  "Ext.ux.event.RecorderManager": [],
  "Taco.view.generalSettings.subform.Rules": [],
  "Taco.view.site.page.Edit": [],
  "Taco.controller.PaymentAndCheckout": [],
  "Taco.core.ux.grid.Header": [],
  "Taco.store.LocalizedStrings": [],
  "Taco.view.navigation.GlobalSearchBox": [],
  "Taco.store.SiteDirectoryNodes": [],
  "Taco.core.ux.browser.Modal": [],
  "Taco.model.SimplegridColumn": [],
  "Taco.view.order.Grid": [],
  "Taco.core.ux.browser.FilterList": [],
  "Taco.core.data.RemoteException": [],
  "Taco.model.InternationalShippingRate": [],
  "Taco.model.ProductType": [],
  "Taco.view.option.preview.RadioButtons": [],
  "Taco.core.ux.CellEditing": [],
  "Taco.core.data.Model": [],
  "Ext.ux.TabScrollerMenu": [],
  "Taco.core.util.Protectable": [],
  "Taco.view.product.subform.Categories": [],
  "Taco.store.ThemeFonts": [],
  "Taco.core.ux.simplegrid.Grid": [],
  "Taco.view.category.Index": [],
  "Taco.model.NavigationItem": [],
  "Taco.view.settings.shipping.Edit": [],
  "Taco.controller.Catalog": [],
  "Ext.ux.LiveSearchGridPanel": [],
  "Taco.store.States": [],
  "Ext.ux.grid.filter.DateFilter": [],
  "Taco.view.settings.paymentAndCheckout.subform.PaymentType": [],
  "Taco.controller.WidgetDefinitions": [],
  "Taco.model.Navigation": [],
  "Taco.store.OptionComboBox": [],
  "Taco.view.site.page.inlineeditors.InlineText": [],
  "Taco.model.CustomerGroup": [],
  "Taco.view.site.navigation.ExternalLinkEditor": [],
  "Ext.ux.BoxReorderer": [],
  "Taco.core.ux.PanelHeader": [],
  "Taco.core.ux.modal.Confirmation": [],
  "Taco.view.site.widget.RecentBlogPosts": [],
  "Taco.view.product.Edit": [],
  "Taco.core.ux.form.SlugField": [],
  "Taco.core.ux.tinymce.WindowManager": [],
  "Taco.store.ThemeListing": [],
  "Taco.model.CouponCode": [],
  "Taco.view.settings.shipping.subform.Custom": [],
  "Taco.Application": [],
  "Taco.core.ux.form.Form": [],
  "Taco.view.order.modal.CapturePayment": [],
  "Taco.model.LocalizedString": [],
  "Taco.view.site.page.settings.CategoryTemplates": [],
  "Taco.view.order.modal.CheckPayment": [],
  "Taco.core.ux.modal.Drawer": [],
  "Taco.model.ShippingCarrierSetting": [],
  "Taco.model.ProductOption": [],
  "Taco.view.option.TempValueEditor": [],
  "Taco.core.ux.tab.Picker": [],
  "Taco.core.ux.form.FileInputButton": [],
  "Taco.core.ux.form.EditorLayout": [],
  "Taco.view.attribute.Index": [],
  "Taco.core.ux.form.FullEditor": [],
  "Taco.model.CustomShippingRate": [],
  "Taco.view.theme.ThemeView": [],
  "Taco.core.util.RangeFilter": [],
  "Taco.view.image.Uploader": [],
  "Taco.view.product.option.VariationGrid": [],
  "Ext.ux.grid.filter.StringFilter": [],
  "Taco.store.WidgetInstances": [],
  "Taco.view.order.modal.PaymentAction": [],
  "Taco.view.site.widget.BlogArchive": [],
  "Taco.view.productType.Index": [],
  "Taco.core.StateManager": [],
  "Taco.view.productType.AttributeGroup": [],
  "Taco.core.context.StoreItem": [],
  "Taco.core.ux.ComplexDataView": [],
  "Taco.core.ux.form.NavForm2": [],
  "Taco.core.ux.grid.RowExpander": [],
  "Taco.controller.PageTemplates": [],
  "Taco.controller.Main": [],
  "Taco.view.product.Modal": [],
  "Taco.core.util.UploadManager": [],
  "Taco.view.account.Overview": [],
  "Taco.core.CTemplate": [],
  "Taco.store.FileManagementFiles": [],
  "Taco.controller.Customers": [],
  "Taco.core.ux.TextFilter": [],
  "Taco.model.Facet": [],
  "Ext.ux.grid.menu.RangeMenu": [],
  "Taco.view.option.Edit": [],
  "Taco.store.ConfiguredShippingRates": [],
  "Taco.model.ThemeListing": [],
  "Taco.core.util.GetsParentPage": [],
  "Taco.core.ux.Hint": [],
  "Taco.view.order.subform.Shipping": [],
  "Taco.view.customers.Form": [],
  "Taco.view.themesettings.Index": [],
  "Taco.view.site.Toolbar": [],
  "Taco.core.ux.TabPanel": [],
  "Taco.view.customers.AddressPanel": [],
  "Taco.view.site.page.hint.Element": [],
  "Taco.view.product.subform.Inventory": [],
  "Taco.store.ShippingCarrierSettings": [],
  "Taco.model.CmsDocumentDraft": [],
  "Taco.view.inventory.Index": [],
  "Taco.view.order.widget.ProductConfigurator": [],
  "Taco.core.ux.grid.Pager": [],
  "Taco.view.site.page.entityAdapters.ProductEntityAdapter": [],
  "Taco.controller.Themesettings": [],
  "Taco.view.site.page.WidgetDragZone": [],
  "Taco.model.UspsSharedShippingMethod": [],
  "Ext.ux.DataTip": [],
  "Taco.model.ProductExtra": [],
  "Taco.core.ux.tab.Tab": [],
  "Ext.ux.ajax.JsonSimlet": [],
  "Taco.view.settings.paymentAndCheckout.subform.LegalInformation": [],
  "Taco.view.order.modal.AddPaymentTransaction": [],
  "Taco.store.Roles": [],
  "Taco.view.customers.ItemBrowser": [],
  "Taco.core.ux.form.StepContainer": [],
  "Taco.model.AccountUser": [],
  "Taco.core.util.TextSelection": [],
  "Taco.view.role.Form": [],
  "Taco.view.order.modal.IssueCredit": [],
  "Taco.view.order.modal.AddPayment": [],
  "Taco.view.site.widget.FacebookComments": [],
  "Taco.core.ux.ListGridToggle": [],
  "Taco.core.ux.form.ColorField": [],
  "Ext.ux.DataView.DragSelector": [],
  "Taco.core.ux.form.UnitField": [],
  "Taco.store.UspsConfigurations": [],
  "Ext.ux.grid.menu.ListMenu": [],
  "Taco.view.order.subform.Subform": [],
  "Taco.core.ux.form.field.MultiSelect": [],
  "Taco.view.site.page.hint.Zone": [],
  "Taco.model.Option": [],
  "Taco.view.role.Index": [],
  "Taco.view.site.page.dataViews.Meta": [],
  "Taco.view.customers.Index": [],
  "Taco.core.ux.action.PrimarySplitButton": [],
  "Taco.store.TempPages": [],
  "Taco.controller.Account": [],
  "Taco.core.Controller": [],
  "Taco.store.CustomerGroupComboBox": [],
  "Taco.model.ItemFilter": [],
  "Taco.model.CartItem": [],
  "Taco.core.ux.ComponentColumn": [],
  "Taco.store.AccountUsers": [],
  "Taco.view.settings.tax.Edit": [],
  "Ext.ux.PreviewPlugin": [],
  "Taco.view.Header": [],
  "Taco.view.site.page.entityAdapters.BaseEntityAdapter": [],
  "Taco.view.email.Edit": [],
  "Ext.ux.ajax.SimXhr": [],
  "Ext.ux.CellDragDrop": [],
  "Taco.core.layout.HFlex": [],
  "Ext.ux.SlidingPager": [],
  "Taco.view.productType.Edit": [],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.grid.filter.NumericFilter": [],
  "Taco.controller.Roles": [],
  "Taco.view.order.modal.ManualPayment": [],
  "Taco.core.context.MasterCatalog": [],
  "Taco.view.Viewport": [],
  "Taco.store.Navigation": [],
  "Ext.ux.event.Recorder": [],
  "Taco.model.InventoryProduct": [],
  "Taco.controller.GeneralSettings": [],
  "Taco.store.OrderNotes": [],
  "Ext.ux.grid.filter.BooleanFilter": [],
  "Taco.view.role.Edit": [],
  "Taco.view.navigation.PrimarySubMenu": [],
  "Taco.store.OrderItems": [],
  "Taco.model.AttributeValue": [],
  "Taco.view.order.modal.ShipmentAction": [],
  "Taco.model.Discount": [],
  "Taco.core.ux.form.Linker": [],
  "Ext.ux.form.SearchField": [],
  "Taco.core.ux.action.Button": [],
  "Taco.view.product.subform.General": [],
  "Taco.view.dashboard.Index": [],
  "Ext.ux.dd.CellFieldDropZone": [],
  "Taco.view.category.Edit": [],
  "Taco.view.settings.tax.Form": [],
  "Taco.store.GeneralSettings": [],
  "Taco.view.productOption.Edit": [],
  "Taco.view.site.navigation.WidgetNav": [],
  "Taco.core.ux.CellEditor": [],
  "Taco.model.PaymentTransaction": [],
  "Taco.view.order.Edit": [],
  "Taco.core.AppState": [],
  "Taco.model.SelectedShippingMethod": [],
  "Ext.ux.grid.filter.ListFilter": [],
  "Taco.view.navigation.SecondaryMenu": [],
  "Taco.store.CmsDocuments": [],
  "Taco.model.TaxRate": [],
  "Taco.store.ProductComboBox": [],
  "Taco.core.layout.Toolbar": [],
  "Taco.view.productType.Form": [],
  "Taco.core.ux.SimpleEditor": [],
  "Taco.view.option.ConfigurableEdit": [],
  "Taco.model.SiteDirectoryNode": [],
  "Taco.core.ux.action.Primary": [],
  "Taco.view.NotifierBar": [],
  "Taco.model.CustomerAccountNote": [],
  "Ext.ux.GMapPanel": [],
  "Taco.store.UspsSharedShippingMethods": [],
  "Taco.store.Attributes": [],
  "Taco.model.TimeZone": [],
  "Taco.core.PageView": [],
  "Taco.core.data.ReadAheadProxy": [],
  "Taco.store.DomesticShippingRates": [],
  "Taco.view.settings.paymentAndCheckout.Form": [],
  "Taco.model.RuntimeProductSearchResult": [],
  "Taco.model.WidgetDefinition": [],
  "Ext.ux.DataView.Animated": [],
  "Taco.core.ux.CountrySelector": [],
  "Taco.core.ux.ScrollSpy": [],
  "Taco.model.PaymentAndCheckout": [],
  "Taco.view.account.AccountInformation": [],
  "Taco.core.ux.simplegrid.Header": [],
  "Taco.controller.Orders": [],
  "Taco.view.account.Billing": [],
  "Taco.core.data.StoreManager": [],
  "Taco.core.ux.action.DirtyButton": [],
  "Ext.ux.statusbar.StatusBar": [
    "Ext.ux.StatusBar"
  ],
  "Taco.controller.Navigation": [],
  "Taco.core.ux.form.Tasks": [],
  "Taco.view.generalSettings.subform.Analytics": [],
  "Taco.core.ux.form.TextAlignment": [],
  "Taco.core.ux.TileView": [],
  "Taco.core.ux.action.PrimaryButton": [],
  "Taco.view.address.AddressForm": [],
  "Taco.controller.Options": [],
  "Taco.shared.model.File": [],
  "Taco.view.site.navigation.PageCreator": [],
  "Taco.view.email.Index": [],
  "Taco.view.product.Index": [],
  "Taco.core.ux.modal.ContentWithActions": [],
  "Taco.model.SiteShippingSettings": [],
  "Taco.model.Attribute": [],
  "Taco.view.option.preview.DropDown": [],
  "Taco.view.product.GlobalForm": [],
  "Taco.view.product.subform.Properties": [],
  "Taco.core.ux.GenEditor": [],
  "Ext.ux.DataView.Draggable": [],
  "Taco.view.order.modal.EditTrackingNumber": [],
  "Taco.view.order.subform.Payment": [],
  "Taco.core.ux.modal.Helper": [],
  "Taco.core.ux.form.BackgroundImagePicker": [],
  "Taco.core.ux.grid.RowBody": [],
  "Taco.store.ProductExtraListItems": [],
  "Taco.view.category.Form": [],
  "Ext.ux.form.ItemSelector": [
    "Ext.ux.ItemSelector"
  ],
  "Ext.ux.Spotlight": [],
  "Taco.core.ux.grid.Panel": [],
  "Taco.view.order.modal.ProductConfigurator": [],
  "Taco.model.ProductImageDocument": [],
  "Taco.core.ux.IndentedTreeColumn": [],
  "Taco.view.site.navigation.PageSettings": [],
  "Taco.model.Order": [],
  "Taco.core.ux.modal.Cover": [],
  "Taco.controller.PendingChanges": [],
  "Taco.model.DomesticShippingRate": [],
  "Taco.view.site.page.hint.Hint": [],
  "Ext.ux.ajax.DataSimlet": [],
  "Taco.core.ux.Panel": [],
  "Taco.model.CmsDocument": [],
  "Taco.core.ux.form.CurrencyField": [],
  "Taco.core.ux.TilePanel": [],
  "Taco.view.site.page.inlineeditors.InlineTags": [],
  "Taco.core.ux.IconSizeSlider": [],
  "Taco.shared.store.Files": [],
  "Taco.view.paymentAndCheckout.RadioList": [],
  "Taco.view.option.valueEditor.TextField": [],
  "Taco.view.product.ImageField": [],
  "Taco.store.SelectedShippingMethods": [],
  "Taco.core.ux.browser.ItemBrowser": [],
  "Taco.core.ux.CheckColumn": [],
  "Taco.view.discount.Edit": [],
  "Taco.core.ux.form.Step": [],
  "Taco.view.site.widget.FeaturedProducts": [],
  "Taco.model.Role": [],
  "Taco.view.site.widget.AddThis": [],
  "Taco.core.ux.form.ModalEditor": [],
  "Taco.view.testing.Shim": [],
  "Taco.model.CountryComboBox": [],
  "Taco.view.site.page.dataViews.Blog": [],
  "Taco.controller.Inventory": [],
  "Taco.view.image.UploadItem": [],
  "Taco.core.ux.HtmlEditor": [],
  "Taco.core.ux.SidebarList": [],
  "Taco.store.CustomerTags": [],
  "Taco.view.generalSettings.subform.About": [],
  "Taco.core.ux.form.EditorWrapper": [],
  "Taco.view.site.widget.HorizontalRule": [],
  "Taco.view.site.page.FieldNodeProcessor": [],
  "Taco.core.ux.DragSource": [],
  "Taco.store.InternationalShippingRates": [],
  "Taco.view.image.UploadModal": [],
  "Taco.core.ux.form.Module": [],
  "Taco.model.TargetedShippingMethod": [],
  "Taco.core.data.AjaxProxy": [],
  "Taco.view.site.page.WidgetDropZone": [],
  "Ext.ux.ProgressBarPager": [],
  "Taco.store.CmsDocumentDrafts": [],
  "Taco.model.ProductComboBox": [],
  "Taco.locale.Strings": [],
  "Taco.model.Behavior": [],
  "Taco.model.Contact": [],
  "Taco.core.ux.FileDragDroppable": [],
  "Taco.view.option.Form": [],
  "Taco.view.site.page.settings.Seo": [],
  "Taco.controller.Errors": [],
  "Taco.store.ItemFilters": [],
  "Taco.core.ux.DragDropZone": [],
  "Taco.view.account.Users": [],
  "Taco.view.site.page.entityAdapters.ExternalLinkEntityAdapter": [],
  "Taco.controller.Sites": [],
  "Taco.view.order.widget.OrderItemGrid": [],
  "Taco.view.discount.Form": [],
  "Taco.model.ActiveRateProvider": [],
  "Ext.ux.ajax.SimManager": [],
  "Taco.view.themesettings.Group": [],
  "Taco.view.site.ToolboxPanel": [],
  "Taco.core.util.ExceptionWhiner": [],
  "Taco.controller.Email": [],
  "Taco.shared.model.FileManagementFile": [],
  "Taco.view.order.widget.Package": [],
  "Taco.store.GatewayDefinitions": [],
  "Taco.model.KeyValuePair": [],
  "Taco.core.ux.action.GridAction": [],
  "Taco.core.ux.form.field.PageTemplate": [],
  "Taco.store.shared.BaseStore": [],
  "Taco.view.product.option.Form": [],
  "Taco.view.paymentAndCheckout.StandaloneAccordion": [],
  "Taco.view.settings.shipping.subform.ShippingPreferences": [],
  "Taco.model.Product": [],
  "Taco.core.ux.form.FieldGroup": [],
  "Taco.view.settings.shipping.Form": [],
  "Taco.view.product.subform.Merchandising": [],
  "Taco.view.fileManager.Associator": [],
  "Taco.view.settings.shipping.subform.MethodsAndRates": [],
  "Taco.view.product.SiteForm": [],
  "Taco.model.WidgetInstance": [],
  "Taco.view.generalSettings.Index": [],
  "Ext.ux.TreePicker": [],
  "Taco.core.layout.VFlex": [],
  "Taco.core.ux.BoxReorderer": [],
  "Ext.ux.data.PagingMemoryProxy": [
    "Ext.data.PagingMemoryProxy"
  ],
  "Taco.view.site.page.Creator": [],
  "Ext.ux.grid.filter.Filter": [],
  "Taco.view.role.BehaviorsForm": [],
  "Ext.ux.GroupTabRenderer": [],
  "Taco.controller.Testing": [],
  "Taco.core.ux.DragHandleColumn": [],
  "Taco.core.ux.content.Sidebar": [],
  "Taco.core.ux.form.FontField": [],
  "Taco.store.InventoryProducts": [],
  "Taco.core.ux.modal.Alert": [],
  "Taco.view.product.Form": [],
  "Taco.view.option.Edit2": [],
  "Taco.core.ux.action.TreeListAction": [],
  "Taco.core.ux.grid.HeaderDropZone": [],
  "Taco.core.FormPanel": [],
  "Taco.store.NavigationTreeNodes": [],
  "Taco.model.UspsConfiguration": [],
  "Taco.model.OrderNote": [],
  "Taco.controller.Themes": [],
  "Taco.core.ux.ColorPicker": [],
  "Taco.core.data.CategoryTreeProxy": [],
  "Taco.model.Shipment": [],
  "Taco.core.ux.FilterableDataView": [],
  "Taco.store.Discounts": [],
  "Taco.core.ux.MultiImageField": [],
  "Ext.ux.DataView.LabelEditor": [],
  "Taco.view.navigation.PrimaryMenuView": [],
  "Taco.core.ux.form.FlexBox": [],
  "Taco.view.site.Toolbox": [],
  "Taco.view.site.widget.TagCollection": [],
  "Taco.core.ux.form.Interface": [],
  "Taco.view.attribute.Form": [],
  "Taco.core.ux.form.DateTime": [],
  "Taco.store.RuntimeProductSearch": [],
  "Taco.model.RuntimeProduct": [],
  "Taco.model.AccountInformation": [],
  "Taco.model.ShippingRate": [],
  "Taco.store.TargetedShippingMethods": [],
  "Taco.store.CategoriesTree": [],
  "Taco.model.CustomerAccount": [],
  "Taco.model.ThemeFont": [],
  "Ext.ux.RowExpander": [],
  "Taco.model.OptionComboBox": [],
  "Taco.model.ProductInCatalogInfo": [],
  "Taco.store.Orders": [],
  "Taco.view.site.page.PageSettingsPanel": [],
  "Taco.view.order.Index": [],
  "Taco.core.ux.action.Action": [],
  "Taco.view.site.page.entityAdapters.CategoryEntityAdapter": [],
  "Taco.store.IpRanges": [],
  "Taco.shared.util.Uploadable": [],
  "Taco.controller.Discounts": [],
  "Taco.core.ux.form.ToggleGroup": [],
  "Taco.store.shared.TreeStore": [],
  "Taco.view.product.subform.OverrideForm": [],
  "Taco.view.site.page.Form": [],
  "Taco.view.discount.Index": [],
  "Taco.core.ux.ClassHandledDragDrop": [],
  "Ext.ux.event.Maker": [],
  "Taco.store.PageTypeDefinitions": [],
  "Taco.store.Categories": [],
  "Taco.view.option.Index": [],
  "Taco.view.site.widget.Editor": [],
  "Taco.store.CountryComboBox": [],
  "Taco.view.account.Navigation": [],
  "Taco.view.site.page.EditSurface": [],
  "Taco.view.testing.EditAddressTest": [],
  "Taco.view.product.AddSiteContainer": [],
  "Taco.store.Customers": []
});
Ext.ClassManager.addNameAliasMappings({
  "Taco.view.settings.paymentAndCheckout.Gateway": [],
  "Taco.view.option.EditModal": [],
  "Taco.model.CustomerGroupComboBox": [],
  "Taco.core.ux.window.WindowWithActions": [
    "widget.taco.windowwithactions"
  ],
  "Taco.core.ux.browser.BrowserPage": [
    "widget.browserpage"
  ],
  "Taco.view.testing.StandaloneOption": [],
  "Taco.view.attribute.Edit": [],
  "Taco.core.ux.action.SplitButton": [
    "widget.taco.splitbutton"
  ],
  "Taco.view.site.page.inlineeditors.InlineHtml": [],
  "Taco.core.ux.CardPanel": [
    "widget.cardpanel"
  ],
  "Taco.view.site.CreateModal": [],
  "Taco.view.site.page.FacetRangeQueryForm": [
    "widget.taco.rangequeryform"
  ],
  "Taco.store.ProductTypes": [],
  "Taco.store.Options": [],
  "Taco.model.User": [],
  "Taco.view.fileManager.Index": [
    "widget.filemanager"
  ],
  "Ext.ux.layout.component.field.BoxSelectField": [
    "layout.boxselectfield"
  ],
  "Taco.view.site.page.settings.Templates": [],
  "Taco.view.site.page.SiteDirectory": [],
  "Taco.view.site.widget.JasonImage": [],
  "Taco.view.order.widget.PaymentPanel": [],
  "Taco.core.ux.modal.BrowserModal": [],
  "Taco.core.ux.BaseGrid": [
    "widget.basegrid"
  ],
  "Taco.model.IpRange": [],
  "Taco.view.order.subform.Detail": [],
  "Taco.model.OrderItem": [],
  "Taco.core.ux.window.Window": [
    "widget.taco.window"
  ],
  "Taco.model.FacetSet": [],
  "Taco.view.site.widget.ColumnDivider": [],
  "Taco.view.productType.AttributeForm": [
    "widget.taco.producttype.attributeform"
  ],
  "Taco.view.error.Index": [],
  "Taco.core.util.FileUploadEvent": [],
  "Taco.view.pageTemplates.Edit": [],
  "Taco.view.customers.Edit": [],
  "Ext.ux.ajax.Simlet": [
    "simlet.basic"
  ],
  "Taco.model.OptionValue": [],
  "Taco.view.site.navigation.Tree": [],
  "Taco.core.ux.BaseCardPanel": [
    "widget.basecardpanel"
  ],
  "Taco.model.GeneralSettings": [],
  "Taco.core.ux.grid.MenuColumn": [
    "widget.taco.menucolumn"
  ],
  "Taco.model.ProductTypeAttribute": [],
  "Taco.view.customers.SearchForm": [],
  "Taco.core.ux.content.Container": [
    "widget.contentcontainer"
  ],
  "Taco.controller.Categories": [],
  "Taco.view.site.page.FacetRangeQueryGroup": [
    "widget.taco.rangequerygroup"
  ],
  "Taco.model.ProductOptionValue": [],
  "Taco.view.product.subform.Shipping": [],
  "Taco.core.ux.EditPanel": [
    "widget.editpanel"
  ],
  "Taco.view.generalSettings.subform.Maintenance": [],
  "Taco.view.navigation.ContextSwitcher": [
    "taco.contextswitcher"
  ],
  "Taco.view.error.Http500": [],
  "Taco.model.ShopperNotes": [],
  "Taco.store.Behaviors": [],
  "Ext.ux.IFrame": [
    "widget.uxiframe"
  ],
  "Taco.core.ux.OptionComboBox": [
    "widget.optioncombobox"
  ],
  "Taco.view.navigation.PrimaryMenu": [],

  "Taco.view.error.Http404": [],
  "Taco.model.ProductProperty": [],
  "Taco.model.StateComboBox": [],
  "Taco.view.pendingchange.Cms": [],
  "Taco.view.site.page.settings.Facets": [],
  "Taco.controller.Products": [],
  "Taco.store.ProductOptionValues": [],
  "Taco.core.ux.EditContainer": [
    "widget.taco.editcontainer"
  ],
  "Taco.view.settings.shipping.subform.ShippingProvider": [],
  "Taco.view.option.valueEditor.MultiValue": [
    "widget.optionvalueeditor"
  ],
  "Taco.model.NavigationTreeNode": [],
  "Taco.view.paymentAndCheckout.FieldDescription": [
    "widget.field-description"
  ],
  "Taco.store.TimeZones": [],
  "Taco.view.catalog.Index": [],
  "Taco.store.TaxRates": [],
  "Taco.core.ux.browser.Browsable": [],
  "Taco.controller.Message": [],
  "Taco.view.order.Header": [],
  "Taco.view.pageTemplate.Index": [
    "widget.pageTemplateIndex"
  ],
  "Taco.core.EventChain": [],
  "Taco.view.settings.paymentAndCheckout.Edit": [],
  "Taco.view.product.subform.Subform": [],
  "Ext.ux.FieldReplicator": [],
  "Taco.view.option.preview.TextField": [],
  "Taco.view.product.subform.Extras": [
    "widget.productextrasform"
  ],
  "Taco.model.ShippingClass": [],
  "Taco.view.order.modal.Address": [],
  "Taco.view.product.subform.SEO": [],
  "Taco.store.CustomerAccountNotes": [],
  "Ext.ux.dd.PanelFieldDragZone": [],
  "Taco.core.ux.content.Body": [
    "widget.contentbody"
  ],
  "Taco.core.ux.ComboFilter": [
    "widget.taco.combofilter"
  ],
  "Taco.core.context.TaContext": [],
  "Taco.view.site.widget.ImagesGallery": [],
  "Taco.core.ux.simplegrid.Body": [
    "widget.simplegridbody"
  ],
  "Taco.view.product.subform.ListExtraEditor": [
    "widget.taco.product.listextraeditor"
  ],
  "Taco.store.Products": [],
  "Taco.core.ux.tinymce.TinyMCE": [
    "widget.tinymcefield"
  ],
  "Taco.core.ux.form.Editor": [
    "widget.formeditor"
  ],
  "Taco.core.ux.form.FontPicker": [
    "widget.fontpicker"
  ],
  "Ext.ux.GroupTabPanel": [
    "widget.grouptabpanel"
  ],
  "Taco.core.ux.modal.Modal": [
    "widget.taco.modal"
  ],
  "Ext.ux.statusbar.ValidationStatus": [],
  "Ext.ux.layout.Center": [
    "layout.ux.center"
  ],
  "Taco.store.WidgetDefinitions": [],
  "Taco.view.settings.shipping.subform.ShippingFrom": [],
  "Taco.view.order.modal.RequestCheck": [],
  "Taco.core.ux.form.TextFieldColumn": [
    "widget.textfieldcolumn"
  ],
  "Taco.model.ProductExtraListItem": [],
  "Taco.model.Address": [],
  "Taco.core.ux.tab.Panel": [
    "widget.taco.tabpanel"
  ],
  "Taco.core.ux.CategoryComboBox": [
    "widget.categorycombobox"
  ],
  "Ext.ux.form.field.BoxSelect": [
    "widget.boxselect",
    "widget.comboboxselect"
  ],
  "Taco.view.paymentAndCheckout.Index": [],
  "Taco.core.ux.form.field.Base": [],
  "Taco.core.ux.content.Header": [
    "widget.contentheader"
  ],
  "Taco.core.ux.OptionValueGrid": [
    "widget.optionvaluegrid"
  ],
  "Taco.core.ContentView": [
    "widget.contentview"
  ],
  "Taco.model.FacetSource": [],
  "Taco.core.context.Site": [],
  "Taco.controller.Attributes": [],
  "Taco.view.site.page.entityAdapters.DocumentEntityAdapter": [],
  "Taco.model.OrderItemDiscount": [],
  "Taco.store.CustomerGroups": [],
  "Ext.ux.event.Player": [],
  "Taco.view.settings.paymentAndCheckout.subform.CheckoutPreference": [],
  "Taco.core.ux.form.NavForm": [
    "widget.taco.navform"
  ],
  "Taco.core.ux.modal.Mini": [
    "widget.minimodal"
  ],
  "Taco.view.navigation.PrimarySubMenuItem": [],
  "Taco.model.ProductVariation": [],
  "Taco.core.ux.action.Secondary": [
    "widget.secondaryaction"
  ],
  "Taco.view.site.page.inlineeditors.InlineImage": [],
  "Taco.model.OrderPaymentInteraction": [],
  "Taco.core.ux.modal.Content": [
    "widget.contentmodal"
  ],
  "Ext.ux.ToolbarDroppable": [],
  "Taco.model.GatewayDefinitions": [],
  "Taco.core.ux.form.BackgroundImageField": [
    "widget.backgroundimagefield"
  ],
  "Taco.controller.ProductTypes": [],
  "Taco.view.inventory.QuantityEdit": [],
  "Taco.core.ux.form.SelectField": [
    "widget.selectfield"
  ],
  "Taco.store.shared.ContainerStore": [],
  "Taco.view.generalSettings.subform.Notifications": [],
  "Ext.ux.TabCloseMenu": [
    "plugin.tabclosemenu"
  ],
  "Taco.view.order.widget.UnpackagedItems": [],
  "Taco.core.ux.form.field.Container": [],
  "Taco.shared.view.field.Image": [
    "widget.taco.imagefield"
  ],
  "Taco.view.themesettings.Section": [
    "widget.themesettingssection"
  ],
  "Taco.core.ux.TreeList": [
    "widget.treelist"
  ],
  "Ext.ux.grid.filter.DateTimeFilter": [
    "gridfilter.datetime"
  ],
  "Taco.model.PaymentReference": [],
  "Taco.core.util.GetsTextFormat": [],
  "Taco.view.site.navigation.Themes": [],
  "Taco.view.generalsettings.Form": [
    "widget.generalsettingseditor"
  ],
  "Ext.ux.grid.FiltersFeature": [
    "feature.filters"
  ],
  "Taco.core.ux.GroupedView": [],
  "Taco.view.Main": [
    "widget.app-main"
  ],
  "Taco.core.ux.modal.SidebarModal": [
    "widget.sidebarmodal"
  ],
  "Taco.view.site.page.settings.General": [],
  "Taco.view.theme.Index": [],
  "Taco.view.address.ModalEditor": [],
  "Taco.controller.Analytics": [],
  "Taco.view.site.page.FacetRangeQuery": [
    "widget.taco.rangequery"
  ],
  "Taco.model.OrderPayment": [],
  "Taco.store.StateComboBox": [
    "widget.statecomboboxstore"
  ],
  "Ext.ux.grid.TransformGrid": [],
  "Taco.view.category.Modal": [],
  "Taco.view.site.page.hint.Widget": [
    "widget.tacohintwidget"
  ],
  "Taco.view.navigation.ContextSwitcherView": [],
  "Taco.core.ux.picker.DateTime": [
    "widget.datetimepicker"
  ],
  "Taco.core.ux.form.TextField": [
    "widget.taco.textfield"
  ],
  "Taco.view.site.page.Shim": [],
  "Taco.view.generalSettings.subform.Tools": [],
  "Ext.ux.event.Driver": [],
  "Ext.ux.ajax.XmlSimlet": [
    "simlet.xml"
  ],
  "Taco.controller.FileManager": [],
  "Taco.controller.Dashboard": [],
  "Taco.core.ux.form.RemovableColumn": [
    "widget.removablecolumn"
  ],
  "Taco.model.PageTypeDefinition": [],
  "Taco.core.ux.CustomerGroupComboBox": [
    "widget.customergroupcombobox"
  ],
  "Taco.controller.Settings": [],
  "Taco.core.ux.form.OnOffSliderButton": [
    "widget.onoffsliderbutton"
  ],
  "Taco.model.Category": [],
  "Ext.ux.form.MultiSelect": [
    "widget.multiselect",
    "widget.multiselectfield"
  ],
  "Taco.core.ux.TabBar": [],
  "Taco.view.product.option.Modal": [],
  "Taco.core.ux.PanelDD": [],
  "Taco.core.ux.QuickAdder": [
    "widget.quickadder"
  ],
  "Taco.view.generalSettings.subform.Robots": [],
  "Taco.core.ux.action.SecondaryButton": [
    "widget.secondarybutton"
  ],
  "Taco.model.OrderSummary": [],
  "Taco.view.customers.GroupsForm": [],
  "Taco.core.ux.IconList": [
    "widget.iconlist"
  ],
  "Ext.ux.event.RecorderManager": [
    "widget.eventrecordermanager"
  ],
  "Taco.view.generalSettings.subform.Rules": [],
  "Taco.view.site.page.Edit": [],
  "Taco.controller.PaymentAndCheckout": [],
  "Taco.core.ux.grid.Header": [],
  "Taco.store.LocalizedStrings": [],
  "Taco.view.navigation.GlobalSearchBox": [],
  "Taco.store.SiteDirectoryNodes": [],
  "Taco.core.ux.browser.Modal": [],
  "Taco.model.SimplegridColumn": [],
  "Taco.view.order.Grid": [],
  "Taco.core.ux.browser.FilterList": [],
  "Taco.core.data.RemoteException": [],
  "Taco.model.InternationalShippingRate": [],
  "Taco.model.ProductType": [],
  "Taco.view.option.preview.RadioButtons": [],
  "Taco.core.ux.CellEditing": [
    "plugin.tacocellediting"
  ],
  "Taco.core.data.Model": [],
  "Ext.ux.TabScrollerMenu": [
    "plugin.tabscrollermenu"
  ],
  "Taco.core.util.Protectable": [],
  "Taco.view.product.subform.Categories": [],
  "Taco.store.ThemeFonts": [],
  "Taco.core.ux.simplegrid.Grid": [
    "widget.simplegrid"
  ],
  "Taco.view.category.Index": [],
  "Taco.model.NavigationItem": [],
  "Taco.view.settings.shipping.Edit": [],
  "Taco.controller.Catalog": [],
  "Ext.ux.LiveSearchGridPanel": [],
  "Taco.store.States": [],
  "Ext.ux.grid.filter.DateFilter": [
    "gridfilter.date"
  ],
  "Taco.view.settings.paymentAndCheckout.subform.PaymentType": [],
  "Taco.controller.WidgetDefinitions": [],
  "Taco.model.Navigation": [],
  "Taco.store.OptionComboBox": [
    "widget.optioncomboboxstore"
  ],
  "Taco.view.site.page.inlineeditors.InlineText": [],
  "Taco.model.CustomerGroup": [],
  "Taco.view.site.navigation.ExternalLinkEditor": [],
  "Ext.ux.BoxReorderer": [],
  "Taco.core.ux.PanelHeader": [],
  "Taco.core.ux.modal.Confirmation": [],
  "Taco.view.site.widget.RecentBlogPosts": [],
  "Taco.view.product.Edit": [],
  "Taco.core.ux.form.SlugField": [
    "widget.slugfield"
  ],
  "Taco.core.ux.tinymce.WindowManager": [],
  "Taco.store.ThemeListing": [],
  "Taco.model.CouponCode": [],
  "Taco.view.settings.shipping.subform.Custom": [],
  "Taco.Application": [],
  "Taco.core.ux.form.Form": [
    "widget.formform"
  ],
  "Taco.view.order.modal.CapturePayment": [],
  "Taco.model.LocalizedString": [],
  "Taco.view.site.page.settings.CategoryTemplates": [],
  "Taco.view.order.modal.CheckPayment": [],
  "Taco.core.ux.modal.Drawer": [
    "widget.drawer"
  ],
  "Taco.model.ShippingCarrierSetting": [],
  "Taco.model.ProductOption": [],
  "Taco.view.option.TempValueEditor": [
    "widget.tempoptionvalueeditor"
  ],
  "Taco.core.ux.tab.Picker": [],
  "Taco.core.ux.form.FileInputButton": [
    "widget.tacofilefield"
  ],
  "Taco.core.ux.form.EditorLayout": [],
  "Taco.view.attribute.Index": [
    "widget.attributeindex"
  ],
  "Taco.core.ux.form.FullEditor": [],
  "Taco.model.CustomShippingRate": [],
  "Taco.view.theme.ThemeView": [
    "widget.widget.taco.themeview"
  ],
  "Taco.core.util.RangeFilter": [
    "widget.rangefilter"
  ],
  "Taco.view.image.Uploader": [
    "widget.imageuploader"
  ],
  "Taco.view.product.option.VariationGrid": [],
  "Ext.ux.grid.filter.StringFilter": [
    "gridfilter.string"
  ],
  "Taco.store.WidgetInstances": [],
  "Taco.view.order.modal.PaymentAction": [],
  "Taco.view.site.widget.BlogArchive": [],
  "Taco.view.productType.Index": [
    "widget.taco.index.producttype"
  ],
  "Taco.core.StateManager": [],
  "Taco.view.productType.AttributeGroup": [
    "widget.taco.producttype.attributegroup"
  ],
  "Taco.core.context.StoreItem": [],
  "Taco.core.ux.ComplexDataView": [
    "widget.complexdataview"
  ],
  "Taco.core.ux.form.NavForm2": [
    "widget.taco.navform2"
  ],
  "Taco.core.ux.grid.RowExpander": [],
  "Taco.controller.PageTemplates": [],
  "Taco.controller.Main": [],
  "Taco.view.product.Modal": [],
  "Taco.core.util.UploadManager": [],
  "Taco.view.account.Overview": [],
  "Taco.core.CTemplate": [],
  "Taco.store.FileManagementFiles": [],
  "Taco.controller.Customers": [],
  "Taco.core.ux.TextFilter": [
    "widget.textfilter"
  ],
  "Taco.model.Facet": [],
  "Ext.ux.grid.menu.RangeMenu": [],
  "Taco.view.option.Edit": [],
  "Taco.store.ConfiguredShippingRates": [],
  "Taco.model.ThemeListing": [],
  "Taco.core.util.GetsParentPage": [],
  "Taco.core.ux.Hint": [
    "widget.hint"
  ],
  "Taco.view.order.subform.Shipping": [],
  "Taco.view.customers.Form": [],
  "Taco.view.themesettings.Index": [
    "widget.themesettingseditor"
  ],
  "Taco.view.site.Toolbar": [],
  "Taco.core.ux.TabPanel": [
    "widget.tacotabpanel"
  ],
  "Taco.view.customers.AddressPanel": [],
  "Taco.view.site.page.hint.Element": [],
  "Taco.view.product.subform.Inventory": [],
  "Taco.store.ShippingCarrierSettings": [],
  "Taco.model.CmsDocumentDraft": [],
  "Taco.view.inventory.Index": [
    "widget.inventoryindex"
  ],
  "Taco.view.order.widget.ProductConfigurator": [],
  "Taco.core.ux.grid.Pager": [
    "widget.taco.pager"
  ],
  "Taco.view.site.page.entityAdapters.ProductEntityAdapter": [],
  "Taco.controller.Themesettings": [],
  "Taco.view.site.page.WidgetDragZone": [],
  "Taco.model.UspsSharedShippingMethod": [],
  "Ext.ux.DataTip": [
    "plugin.datatip"
  ],
  "Taco.model.ProductExtra": [],
  "Taco.core.ux.tab.Tab": [
    "widget.formtab"
  ],
  "Ext.ux.ajax.JsonSimlet": [
    "simlet.json"
  ],
  "Taco.view.settings.paymentAndCheckout.subform.LegalInformation": [],
  "Taco.view.order.modal.AddPaymentTransaction": [],
  "Taco.store.Roles": [],
  "Taco.view.customers.ItemBrowser": [
    "widget.customersbrowser"
  ],
  "Taco.core.ux.form.StepContainer": [
    "widget.formstepcontainer"
  ],
  "Taco.model.AccountUser": [],
  "Taco.core.util.TextSelection": [],
  "Taco.view.role.Form": [],
  "Taco.view.order.modal.IssueCredit": [],
  "Taco.view.order.modal.AddPayment": [],
  "Taco.view.site.widget.FacebookComments": [],
  "Taco.core.ux.ListGridToggle": [
    "widget.listgridtoggle"
  ],
  "Taco.core.ux.form.ColorField": [
    "widget.colorfield"
  ],
  "Ext.ux.DataView.DragSelector": [],
  "Taco.core.ux.form.UnitField": [
    "widget.unitfield"
  ],
  "Taco.store.UspsConfigurations": [],
  "Ext.ux.grid.menu.ListMenu": [],
  "Taco.view.order.subform.Subform": [
    "widget.taco.order.subform"
  ],
  "Taco.core.ux.form.field.MultiSelect": [
    "widget.taco.field.multiselect"
  ],
  "Taco.view.site.page.hint.Zone": [
    "widget.tacohintzone"
  ],
  "Taco.model.Option": [],
  "Taco.view.role.Index": [],
  "Taco.view.site.page.dataViews.Meta": [],
  "Taco.view.customers.Index": [
    "widget.taco.index.customer"
  ],
  "Taco.core.ux.action.PrimarySplitButton": [
    "widget.primarysplitbutton"
  ],
  "Taco.store.TempPages": [],
  "Taco.controller.Account": [],
  "Taco.core.Controller": [],
  "Taco.store.CustomerGroupComboBox": [],
  "Taco.model.ItemFilter": [],
  "Taco.model.CartItem": [],
  "Taco.core.ux.ComponentColumn": [
    "widget.componentcolumn"
  ],
  "Taco.store.AccountUsers": [],
  "Taco.view.settings.tax.Edit": [],
  "Ext.ux.PreviewPlugin": [
    "plugin.preview"
  ],
  "Taco.view.Header": [],
  "Taco.view.site.page.entityAdapters.BaseEntityAdapter": [],
  "Taco.view.email.Edit": [],
  "Ext.ux.ajax.SimXhr": [],
  "Ext.ux.CellDragDrop": [
    "plugin.celldragdrop"
  ],
  "Taco.core.layout.HFlex": [
    "layout.hflex"
  ],
  "Ext.ux.SlidingPager": [],
  "Taco.view.productType.Edit": [],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.grid.filter.NumericFilter": [
    "gridfilter.numeric"
  ],
  "Taco.controller.Roles": [],
  "Taco.view.order.modal.ManualPayment": [],
  "Taco.core.context.MasterCatalog": [],
  "Taco.view.Viewport": [],
  "Taco.store.Navigation": [],
  "Ext.ux.event.Recorder": [],
  "Taco.model.InventoryProduct": [],
  "Taco.controller.GeneralSettings": [],
  "Taco.store.OrderNotes": [],
  "Ext.ux.grid.filter.BooleanFilter": [
    "gridfilter.boolean"
  ],
  "Taco.view.role.Edit": [
    "widget.rolefulledit"
  ],
  "Taco.view.navigation.PrimarySubMenu": [],
  "Taco.store.OrderItems": [],
  "Taco.model.AttributeValue": [],
  "Taco.view.order.modal.ShipmentAction": [],
  "Taco.model.Discount": [],
  "Taco.core.ux.form.Linker": [
    "widget.linker"
  ],
  "Ext.ux.form.SearchField": [
    "widget.searchfield"
  ],
  "Taco.core.ux.action.Button": [
    "widget.taco.button"
  ],
  "Taco.view.product.subform.General": [],
  "Taco.view.dashboard.Index": [],
  "Ext.ux.dd.CellFieldDropZone": [],
  "Taco.view.category.Edit": [
    "widget.categoryfulledit"
  ],
  "Taco.view.settings.tax.Form": [],
  "Taco.store.GeneralSettings": [],
  "Taco.view.productOption.Edit": [
    "widget.productOptionedit"
  ],
  "Taco.view.site.navigation.WidgetNav": [],
  "Taco.core.ux.CellEditor": [
    "plugin.tacocelleditor"
  ],
  "Taco.model.PaymentTransaction": [],
  "Taco.view.order.Edit": [],
  "Taco.core.AppState": [],
  "Taco.model.SelectedShippingMethod": [],
  "Ext.ux.grid.filter.ListFilter": [
    "gridfilter.list"
  ],
  "Taco.view.navigation.SecondaryMenu": [
    "widget.secondarymenu"
  ],
  "Taco.store.CmsDocuments": [],
  "Taco.model.TaxRate": [],
  "Taco.store.ProductComboBox": [],
  "Taco.core.layout.Toolbar": [],
  "Taco.view.productType.Form": [],
  "Taco.core.ux.SimpleEditor": [
    "widget.simpleeditor"
  ],
  "Taco.view.option.ConfigurableEdit": [
    "widget.configurableoptionedit"
  ],
  "Taco.model.SiteDirectoryNode": [],
  "Taco.core.ux.action.Primary": [
    "widget.primaryaction"
  ],
  "Taco.view.NotifierBar": [
    "widget.notifierbar"
  ],
  "Taco.model.CustomerAccountNote": [],
  "Ext.ux.GMapPanel": [
    "widget.gmappanel"
  ],
  "Taco.store.UspsSharedShippingMethods": [],
  "Taco.store.Attributes": [],
  "Taco.model.TimeZone": [],
  "Taco.core.PageView": [],
  "Taco.core.data.ReadAheadProxy": [
    "proxy.readahead"
  ],
  "Taco.store.DomesticShippingRates": [],
  "Taco.view.settings.paymentAndCheckout.Form": [],
  "Taco.model.RuntimeProductSearchResult": [],
  "Taco.model.WidgetDefinition": [],
  "Ext.ux.DataView.Animated": [],
  "Taco.core.ux.CountrySelector": [
    "widget.countryselector"
  ],
  "Taco.core.ux.ScrollSpy": [],
  "Taco.model.PaymentAndCheckout": [],
  "Taco.view.account.AccountInformation": [],
  "Taco.core.ux.simplegrid.Header": [
    "widget.simplegridheader"
  ],
  "Taco.controller.Orders": [],
  "Taco.view.account.Billing": [],
  "Taco.core.data.StoreManager": [],
  "Taco.core.ux.action.DirtyButton": [
    "widget.dirtybutton"
  ],
  "Ext.ux.statusbar.StatusBar": [
    "widget.statusbar"
  ],
  "Taco.controller.Navigation": [],
  "Taco.core.ux.form.Tasks": [],
  "Taco.view.generalSettings.subform.Analytics": [],
  "Taco.core.ux.form.TextAlignment": [
    "widget.alignfield"
  ],
  "Taco.core.ux.TileView": [
    "widget.tileview"
  ],
  "Taco.core.ux.action.PrimaryButton": [
    "widget.primarybutton"
  ],
  "Taco.view.address.AddressForm": [],
  "Taco.controller.Options": [],
  "Taco.shared.model.File": [],
  "Taco.view.site.navigation.PageCreator": [],
  "Taco.view.email.Index": [],
  "Taco.view.product.Index": [
    "widget.prodindex"
  ],
  "Taco.core.ux.modal.ContentWithActions": [
    "widget.selectormodal"
  ],
  "Taco.model.SiteShippingSettings": [],
  "Taco.model.Attribute": [],
  "Taco.view.option.preview.DropDown": [],
  "Taco.view.product.GlobalForm": [
    "widget.productglobalform"
  ],
  "Taco.view.product.subform.Properties": [
    "widget.productpropertiesform"
  ],
  "Taco.core.ux.GenEditor": [],
  "Ext.ux.DataView.Draggable": [],
  "Taco.view.order.modal.EditTrackingNumber": [],
  "Taco.view.order.subform.Payment": [],
  "Taco.core.ux.modal.Helper": [
    "widget.helpermodal"
  ],
  "Taco.core.ux.form.BackgroundImagePicker": [
    "widget.backgroundimagepicker"
  ],
  "Taco.core.ux.grid.RowBody": [
    "feature.taco.rowbody"
  ],
  "Taco.store.ProductExtraListItems": [],
  "Taco.view.category.Form": [],
  "Ext.ux.form.ItemSelector": [
    "widget.itemselector",
    "widget.itemselectorfield"
  ],
  "Ext.ux.Spotlight": [],
  "Taco.core.ux.grid.Panel": [
    "widget.taco.gridpanel"
  ],
  "Taco.view.order.modal.ProductConfigurator": [],
  "Taco.model.ProductImageDocument": [],
  "Taco.core.ux.IndentedTreeColumn": [
    "widget.indentedtreecolumn"
  ],
  "Taco.view.site.navigation.PageSettings": [],
  "Taco.model.Order": [],
  "Taco.core.ux.modal.Cover": [],
  "Taco.controller.PendingChanges": [],
  "Taco.model.DomesticShippingRate": [],
  "Taco.view.site.page.hint.Hint": [],
  "Ext.ux.ajax.DataSimlet": [],
  "Taco.core.ux.Panel": [],
  "Taco.model.CmsDocument": [],
  "Taco.core.ux.form.CurrencyField": [
    "widget.currencyfield"
  ],
  "Taco.core.ux.TilePanel": [
    "widget.tilepanel"
  ],
  "Taco.view.site.page.inlineeditors.InlineTags": [],
  "Taco.core.ux.IconSizeSlider": [
    "widget.iconsizeslider"
  ],
  "Taco.shared.store.Files": [],
  "Taco.view.paymentAndCheckout.RadioList": [
    "widget.radiolist"
  ],
  "Taco.view.option.valueEditor.TextField": [
    "widget.optionvaluetext"
  ],
  "Taco.view.product.ImageField": [],
  "Taco.store.SelectedShippingMethods": [],
  "Taco.core.ux.browser.ItemBrowser": [
    "widget.itembrowser"
  ],
  "Taco.core.ux.CheckColumn": [
    "widget.checkcolumn"
  ],
  "Taco.view.discount.Edit": [],
  "Taco.core.ux.form.Step": [
    "widget.formstep"
  ],
  "Taco.view.site.widget.FeaturedProducts": [],
  "Taco.model.Role": [],
  "Taco.view.site.widget.AddThis": [],
  "Taco.core.ux.form.ModalEditor": [],
  "Taco.view.testing.Shim": [],
  "Taco.model.CountryComboBox": [],
  "Taco.view.site.page.dataViews.Blog": [],
  "Taco.controller.Inventory": [],
  "Taco.view.image.UploadItem": [
    "widget.uploaditem"
  ],
  "Taco.core.ux.HtmlEditor": [
    "widget.tacohtmleditor"
  ],
  "Taco.core.ux.SidebarList": [
    "widget.sidebarlist"
  ],
  "Taco.store.CustomerTags": [],
  "Taco.view.generalSettings.subform.About": [],
  "Taco.core.ux.form.EditorWrapper": [],
  "Taco.view.site.widget.HorizontalRule": [],
  "Taco.view.site.page.FieldNodeProcessor": [],
  "Taco.core.ux.DragSource": [],
  "Taco.store.InternationalShippingRates": [],
  "Taco.view.image.UploadModal": [],
  "Taco.core.ux.form.Module": [
    "widget.formmodule"
  ],
  "Taco.model.TargetedShippingMethod": [],
  "Taco.core.data.AjaxProxy": [
    "proxy.ajaxproxy"
  ],
  "Taco.view.site.page.WidgetDropZone": [],
  "Ext.ux.ProgressBarPager": [],
  "Taco.store.CmsDocumentDrafts": [],
  "Taco.model.ProductComboBox": [],
  "Taco.locale.Strings": [],
  "Taco.model.Behavior": [],
  "Taco.model.Contact": [],
  "Taco.core.ux.FileDragDroppable": [],
  "Taco.view.option.Form": [],
  "Taco.view.site.page.settings.Seo": [],
  "Taco.controller.Errors": [],
  "Taco.store.ItemFilters": [],
  "Taco.core.ux.DragDropZone": [
    "widget.dragdropzone"
  ],
  "Taco.view.account.Users": [],
  "Taco.view.site.page.entityAdapters.ExternalLinkEntityAdapter": [],
  "Taco.controller.Sites": [],
  "Taco.view.order.widget.OrderItemGrid": [],
  "Taco.view.discount.Form": [],
  "Taco.model.ActiveRateProvider": [],
  "Ext.ux.ajax.SimManager": [],
  "Taco.view.themesettings.Group": [
    "widget.themesettingsgroup"
  ],
  "Taco.view.site.ToolboxPanel": [],
  "Taco.core.util.ExceptionWhiner": [],
  "Taco.controller.Email": [],
  "Taco.shared.model.FileManagementFile": [],
  "Taco.view.order.widget.Package": [],
  "Taco.store.GatewayDefinitions": [],
  "Taco.model.KeyValuePair": [],
  "Taco.core.ux.action.GridAction": [
    "widget.gridaction"
  ],
  "Taco.core.ux.form.field.PageTemplate": [
    "widget.taco.field.pagetemplate"
  ],
  "Taco.store.shared.BaseStore": [],
  "Taco.view.product.option.Form": [
    "widget.optionproductform"
  ],
  "Taco.view.paymentAndCheckout.StandaloneAccordion": [
    "widget.standalone-accordion"
  ],
  "Taco.view.settings.shipping.subform.ShippingPreferences": [],
  "Taco.model.Product": [],
  "Taco.core.ux.form.FieldGroup": [],
  "Taco.view.settings.shipping.Form": [],
  "Taco.view.product.subform.Merchandising": [],
  "Taco.view.fileManager.Associator": [],
  "Taco.view.settings.shipping.subform.MethodsAndRates": [],
  "Taco.view.product.SiteForm": [
    "widget.productsiteform"
  ],
  "Taco.model.WidgetInstance": [],
  "Taco.view.generalSettings.Index": [],
  "Ext.ux.TreePicker": [
    "widget.treepicker"
  ],
  "Taco.core.layout.VFlex": [
    "layout.vflex"
  ],
  "Taco.core.ux.BoxReorderer": [],
  "Ext.ux.data.PagingMemoryProxy": [
    "proxy.pagingmemory"
  ],
  "Taco.view.site.page.Creator": [
    "widget.pagecreator"
  ],
  "Ext.ux.grid.filter.Filter": [],
  "Taco.view.role.BehaviorsForm": [],
  "Ext.ux.GroupTabRenderer": [
    "plugin.grouptabrenderer"
  ],
  "Taco.controller.Testing": [],
  "Taco.core.ux.DragHandleColumn": [
    "widget.draghandlecolumn"
  ],
  "Taco.core.ux.content.Sidebar": [
    "widget.sidebar"
  ],
  "Taco.core.ux.form.FontField": [
    "widget.fontfield"
  ],
  "Taco.store.InventoryProducts": [],
  "Taco.core.ux.modal.Alert": [],
  "Taco.view.product.Form": [],
  "Taco.view.option.Edit2": [],
  "Taco.core.ux.action.TreeListAction": [
    "widget.treelistaction"
  ],
  "Taco.core.ux.grid.HeaderDropZone": [],
  "Taco.core.FormPanel": [
    "widget.formpanel"
  ],
  "Taco.store.NavigationTreeNodes": [],
  "Taco.model.UspsConfiguration": [],
  "Taco.model.OrderNote": [],
  "Taco.controller.Themes": [],
  "Taco.core.ux.ColorPicker": [],
  "Taco.core.data.CategoryTreeProxy": [
    "proxy.categorytree"
  ],
  "Taco.model.Shipment": [],
  "Taco.core.ux.FilterableDataView": [
    "widget.filterabledataview"
  ],
  "Taco.store.Discounts": [],
  "Taco.core.ux.MultiImageField": [
    "widget.multiimagefield"
  ],
  "Ext.ux.DataView.LabelEditor": [],
  "Taco.view.navigation.PrimaryMenuView": [],
  "Taco.core.ux.form.FlexBox": [
    "layout.formflexbox",
    "widget.formflexbox"
  ],
  "Taco.view.site.Toolbox": [
    "widget.toolbox"
  ],
  "Taco.view.site.widget.TagCollection": [],
  "Taco.core.ux.form.Interface": [],
  "Taco.view.attribute.Form": [],
  "Taco.core.ux.form.DateTime": [
    "widget.datetime"
  ],
  "Taco.store.RuntimeProductSearch": [],
  "Taco.model.RuntimeProduct": [],
  "Taco.model.AccountInformation": [],
  "Taco.model.ShippingRate": [],
  "Taco.store.TargetedShippingMethods": [],
  "Taco.store.CategoriesTree": [],
  "Taco.model.CustomerAccount": [],
  "Taco.model.ThemeFont": [],
  "Ext.ux.RowExpander": [
    "plugin.rowexpander"
  ],
  "Taco.model.OptionComboBox": [],
  "Taco.model.ProductInCatalogInfo": [],
  "Taco.store.Orders": [],
  "Taco.view.site.page.PageSettingsPanel": [
    "widget.widget.pagesettingspanel"
  ],
  "Taco.view.order.Index": [
    "widget.orderindex"
  ],
  "Taco.core.ux.action.Action": [
    "widget.action"
  ],
  "Taco.view.site.page.entityAdapters.CategoryEntityAdapter": [],
  "Taco.store.IpRanges": [],
  "Taco.shared.util.Uploadable": [],
  "Taco.controller.Discounts": [],
  "Taco.core.ux.form.ToggleGroup": [
    "widget.togglegroup"
  ],
  "Taco.store.shared.TreeStore": [],
  "Taco.view.product.subform.OverrideForm": [
    "widget.productoverride"
  ],
  "Taco.view.site.page.Form": [
    "widget.inlineeditor"
  ],
  "Taco.view.discount.Index": [
    "widget.discountlist"
  ],
  "Taco.core.ux.ClassHandledDragDrop": [
    "plugin.classhandleddragdrop"
  ],
  "Ext.ux.event.Maker": [],
  "Taco.store.PageTypeDefinitions": [],
  "Taco.store.Categories": [],
  "Taco.view.option.Index": [
    "widget.optionindex"
  ],
  "Taco.view.site.widget.Editor": [],
  "Taco.store.CountryComboBox": [
    "widget.countrycomboboxstore"
  ],
  "Taco.view.account.Navigation": [],
  "Taco.view.site.page.EditSurface": [
    "widget.editsurface"
  ],
  "Taco.view.testing.EditAddressTest": [],
  "Taco.view.product.AddSiteContainer": [],
  "Taco.store.Customers": []
});
